Repository mission-apprentissage/api-apprentissage, pull requests merged in 2024-09, with the labels that each got.

#148 feat: ajout organisation
  .infra/files/configs/mongodb/seed.gpg
  .infra/files/scripts/seed.sh
  .talismanrc
  server/src/actions/auth.actions.ts
  server/src/migrations/20240904153957-add-organisation.ts
  server/src/server/routes/_private/admin/organisations.routes.ts
  server/src/server/routes/_private/admin/user.routes.ts
  server/src/server/routes/_private/auth.route.test.ts
  server/src/server/routes/routes.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/fixtures/user.model.fixture.ts
  shared/src/models/models.ts
  shared/src/models/organisation.model.ts
  shared/src/models/user.model.ts
  shared/src/routes/_private/admin/organisation.admin.routes.ts
  shared/src/routes/_private/admin/users.admin.routes.ts
  shared/src/routes/index.ts
  ui/app/admin/organisations/components/CreateOrganisation.tsx
  ui/app/admin/organisations/components/OrganisationList.tsx
  ui/app/admin/organisations/page.tsx
  ui/app/admin/utilisateurs/[id]/components/UserView.tsx
  ui/app/admin/utilisateurs/[id]/page.tsx
  ui/app/admin/utilisateurs/components/UserList.tsx
  ui/app/error.tsx
  ui/components/header/header.utils.ts
  ui/utils/date.utils.ts
  ui/utils/routes.utils.ts
Labels: ignore-for-release

#149 chore: reduce talisman config
  .talismanrc
Labels: ignore-for-release

#150 feat: add api token certificates
  .infra/.env_server
  .infra/docker-compose.preview.yml
  .infra/docker-compose.production.yml
  .infra/vault/vault.yml
  .talismanrc
  docker-compose.yml
  server/.env.test
  server/src/config.ts
  server/src/dev.ts
  server/src/index.ts
  server/src/main.ts
  server/tsup.config.ts
Labels: ignore-for-release

#154 feat: route de recherche d'opportunités d'emploi La bonne alternance
  sdk/README.md
  sdk/src/client/certification/certification.module.test.ts
  sdk/src/client/client.ts
  sdk/src/client/job/__snapshots__/job.module.test.ts.snap
  sdk/src/client/job/job.module.test.ts
  sdk/src/client/job/job.module.ts
  sdk/src/client/organisme/organisme.module.test.ts
Labels: enhancement

#156 fix(ui): ajout du contenu de la page accessibilite
  ui/app/accessibilite/page.tsx
Labels: bug

#147 feat: ajout du lien page statistiques dans le footer
  server/src/migrations/20240904102312-update-mia-users.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/user.model.ts
  ui/app/auth/inscription/page.tsx
  ui/components/Footer.tsx
Labels: enhancement

#155 fix: documentation technique de la route de recherche d'opportunitées d'emploi
  sdk/src/models/job/job.model.ts
  sdk/src/routes/job.routes.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: bug

#157 feat: création et modification d'offre d'emploi La bonne alternance
  .talismanrc
  sdk/src/client/client.ts
  sdk/src/client/job/__snapshots__/job.module.test.ts.snap
  sdk/src/client/job/job.module.test.ts
  sdk/src/client/job/job.module.ts
  sdk/src/external/laBonneAlternance.api.test.ts
  sdk/src/external/laBonneAlternance.api.ts
  sdk/src/models/job/job.model.test.ts
  sdk/src/models/job/job.model.ts
  sdk/src/routes/index.ts
  sdk/src/routes/job.routes.ts
  sdk/src/utils/date.primitives.ts
  sdk/tsconfig.json
  server/src/actions/auth.actions.ts
  server/src/commands.ts
  server/src/migrations/20240916062602-habilitations.ts
  server/src/server/routes/_private/admin/organisations.routes.ts
  server/src/server/routes/_private/auth.route.test.ts
  server/src/server/routes/job/job.route.test.ts
  server/src/server/routes/job/job.routes.ts
  server/src/services/apis/lba/lba.api.test.ts
  server/src/services/apis/lba/lba.api.ts
  server/src/services/jobs/job.service.test.ts
  server/src/services/jobs/job.service.ts
  server/src/services/mailer/mailer.ts
  server/src/services/security/accessTokenService.ts
  server/src/services/security/authenticationService.test.ts
  server/src/services/security/authenticationService.ts
  server/src/services/security/authorisationService.test.ts
  server/src/services/security/authorisationService.ts
  server/tsconfig.json
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/models/fixtures/index.ts
  shared/src/models/fixtures/organisation.model.fixture.ts
  shared/src/models/fixtures/user.model.fixture.ts
  shared/src/models/organisation.model.ts
  shared/src/routes/common.routes.ts
  shared/src/routes/index.ts
  shared/src/routes/job.routes.ts
  shared/src/security/permissions.ts
  shared/tsconfig.json
  tsconfig.json
  ui/tsconfig.json
Labels: enhancement

#162 feat: page d'administration des habilitations
  server/src/server/routes/_private/admin/organisations.routes.ts
  shared/src/models/organisation.model.ts
  shared/src/routes/_private/admin/organisation.admin.routes.ts
  shared/src/routes/index.ts
  ui/app/admin/organisations/[id]/components/OrganisationView.tsx
  ui/app/admin/organisations/[id]/page.tsx
  ui/app/admin/organisations/components/OrganisationList.tsx
  ui/utils/routes.utils.ts
Labels: ignore-for-release

#158 feat: update api description wording for certification / organismes
  sdk/src/routes/certification.routes.ts
  sdk/src/routes/organisme.routes.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: ignore-for-release

#159 feat: update vers le dernier Kit Apprentissage
  server/static/kit_apprentissage/Kit_apprentissage_20240827.xlsx
Labels: ignore-for-release

#163 feat: add 409 http conflict lba
  sdk/src/models/organisme/organismes.primitives.ts
  sdk/src/routes/errors.routes.ts
  server/src/jobs/importer/npec/npec.importer.test.ts
  server/src/services/apis/lba/lba.api.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/helpers/openapi/generateOpenapi.ts
  shared/src/routes/common.routes.ts
Labels: ignore-for-release

#167 fix: technical doc language detection
  ui/app/documentation-technique/components/redoc.tsx
  ui/app/documentation-technique/page.tsx
  ui/package.json
  yarn.lock
Labels: ignore-for-release

#169 feat: english job create & update doc
  .talismanrc
  sdk/src/docs/internal.ts
  sdk/src/docs/routes/jobOfferCreate/jobOfferCreate.route.doc.ts
  sdk/src/docs/routes/jobOfferUpdate/jobOfferUpdate.route.doc.ts
  sdk/src/docs/types.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/helpers/openapi/generateOpenapi.ts
  shared/src/routes/job.routes.ts
Labels: ignore-for-release

#171 feat: upgrade dependencies
  package.json
  sdk/package.json
  sdk/tsconfig.json
  server/package.json
  server/src/server/server.ts
  server/src/services/sentry/sentry.ts
  server/tsconfig.json
  shared/package.json
  shared/tsconfig.json
  ui/app/StartDsfr.tsx
  ui/app/defaultColorScheme.ts
  ui/app/layout.tsx
  ui/instrumentation.ts
  ui/next.config.mjs
  ui/package.json
  ui/sentry.client.config.ts
  ui/sentry.edge.config.ts
  ui/sentry.server.config.ts
  yarn.lock
Labels: ignore-for-release

#173 feat: add addOperationDoc
  sdk/src/docs/routes/jobOfferCreate/jobOfferCreate.route.doc.ts
  sdk/src/docs/routes/jobSearch/jobSearch.route.doc.ts
  sdk/src/docs/types.ts
  sdk/src/utils/zodWithOpenApi.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/routes/job.routes.ts
Labels: ignore-for-release

#176 feat: normalise UAI parameters
  sdk/src/models/organisme/organismes.primitives.test.ts
  sdk/src/models/organisme/organismes.primitives.ts
Labels: bug

#177 chore: move certification doc out from swagger file
  sdk/src/docs/models/certification/certification.model.doc.ts
  sdk/src/docs/models/certification/docs/base_legale.cfd.abrogation.notes.md
  sdk/src/docs/models/certification/docs/base_legale.cfd.abrogation.notes.md.ts
  sdk/src/docs/models/certification/docs/base_legale.cfd.creation.notes.md
  sdk/src/docs/models/certification/docs/base_legale.cfd.creation.notes.md.ts
  sdk/src/docs/models/certification/docs/continuite.description.cfd.notes.md
  sdk/src/docs/models/certification/docs/continuite.description.cfd.notes.md.ts
  sdk/src/docs/models/certification/docs/domaines.nsf.cfd.notes.md
  sdk/src/docs/models/certification/docs/domaines.nsf.cfd.notes.md.ts
  sdk/src/docs/models/certification/docs/intitule.niveau.cfd.europeen.notes.md
  sdk/src/docs/models/certification/docs/intitule.niveau.cfd.europeen.notes.md.ts
  sdk/src/docs/models/certification/docs/periode_validite.rncp.activation.notes.md
  sdk/src/docs/models/certification/docs/periode_validite.rncp.activation.notes.md.ts
  sdk/src/models/certification/certification.model.openapi.ts
  sdk/src/utils/zodWithOpenApi.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: ignore-for-release

#178 chore: normalize error response doc
  sdk/src/models/certification/certification.primitives.ts
  sdk/src/models/errors/errors.model.openapi.ts
  sdk/src/models/organisme/organismes.primitives.ts
  sdk/src/utils/zodWithOpenApi.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/helpers/openapi/generateOpenapi.ts
  shared/src/routes/certification.routes.ts
  shared/src/routes/common.routes.ts
  shared/src/routes/healthcheck.routes.ts
  shared/src/routes/job.routes.ts
  shared/src/routes/organisme.routes.ts
  shared/src/zod/date.primitives.ts
  ui/app/i18n/StartIntl.tsx
Labels: ignore-for-release

#179 feat: prepare model translation
  sdk/src/docs/models/certification/certification.model.doc.ts
  sdk/src/docs/models/job/offer_read.model.doc.ts
  sdk/src/docs/models/job/offer_read_docs/offer.status.description.md
  sdk/src/docs/models/job/offer_read_docs/offer.status.description.md.ts
  sdk/src/docs/models/job/offer_write.model.doc.ts
  sdk/src/docs/models/job/recruiter.model.doc.ts
  sdk/src/docs/routes/jobOfferCreate/jobOfferCreate.route.doc.ts
  sdk/src/docs/routes/jobOfferUpdate/jobOfferUpdate.route.doc.ts
  sdk/src/docs/routes/jobSearch/jobSearch.route.doc.ts
  sdk/src/docs/types.ts
  sdk/src/utils/zodWithOpenApi.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  ui/app/[lang]/explorer/certifications/components/CatalogueData.tsx
  ui/app/[lang]/explorer/certifications/components/GoodToKnow.tsx
Labels: ignore-for-release

#180 feat: lang param in doc
  sdk/src/docs/models/job/offer_read.model.doc.ts
  sdk/src/docs/models/job/offer_read_docs/contract.description.md
  sdk/src/docs/models/job/offer_read_docs/contract.description.md.ts
  sdk/src/docs/models/job/offer_read_docs/en/contract.description.md
  sdk/src/docs/models/job/offer_read_docs/en/contract.description.md.ts
  sdk/src/docs/models/job/offer_read_docs/en/offer.description.md
  sdk/src/docs/models/job/offer_read_docs/en/offer.description.md.ts
  sdk/src/docs/models/job/offer_read_docs/en/offer.publication.description.md
  sdk/src/docs/models/job/offer_read_docs/en/offer.publication.description.md.ts
  sdk/src/docs/models/job/offer_read_docs/en/offer.status.description.md
  sdk/src/docs/models/job/offer_read_docs/en/offer.status.description.md.ts
  sdk/src/docs/models/job/offer_read_docs/fr/contract.description.md
  sdk/src/docs/models/job/offer_read_docs/fr/contract.description.md.ts
  sdk/src/docs/models/job/offer_read_docs/fr/offer.description.md
  sdk/src/docs/models/job/offer_read_docs/fr/offer.description.md.ts
  sdk/src/docs/models/job/offer_read_docs/fr/offer.publication.description.md
  sdk/src/docs/models/job/offer_read_docs/fr/offer.publication.description.md.ts
  sdk/src/docs/models/job/offer_read_docs/fr/offer.status.description.md
  sdk/src/docs/models/job/offer_read_docs/fr/offer.status.description.md.ts
  sdk/src/docs/models/job/offer_write.model.doc.ts
  sdk/src/docs/models/job/offer_write_docs/en/apply.description.md
  sdk/src/docs/models/job/offer_write_docs/en/apply.description.md.ts
  sdk/src/docs/models/job/offer_write_docs/fr/apply.description.md
  sdk/src/docs/models/job/offer_write_docs/fr/apply.description.md.ts
  sdk/src/docs/models/job/recruiter.model.doc.ts
  sdk/src/docs/models/job/recruiter_docs/en/apply.description.md
  sdk/src/docs/models/job/recruiter_docs/en/apply.description.md.ts
  sdk/src/docs/models/job/recruiter_docs/en/identifier.description.md
  sdk/src/docs/models/job/recruiter_docs/en/identifier.description.md.ts
  sdk/src/docs/models/job/recruiter_docs/en/workplace.description.md
  sdk/src/docs/models/job/recruiter_docs/en/workplace.description.md.ts
  sdk/src/docs/models/job/recruiter_docs/en/workplace.domain.description.md
  sdk/src/docs/models/job/recruiter_docs/en/workplace.domain.description.md.ts
  sdk/src/docs/models/job/recruiter_docs/en/workplace.location.description.md
  sdk/src/docs/models/job/recruiter_docs/en/workplace.location.description.md.ts
  sdk/src/docs/models/job/recruiter_docs/fr/apply.description.md
  sdk/src/docs/models/job/recruiter_docs/fr/apply.description.md.ts
  sdk/src/docs/models/job/recruiter_docs/fr/identifier.description.md
  sdk/src/docs/models/job/recruiter_docs/fr/identifier.description.md.ts
  sdk/src/docs/models/job/recruiter_docs/fr/workplace.description.md
  sdk/src/docs/models/job/recruiter_docs/fr/workplace.description.md.ts
  sdk/src/docs/models/job/recruiter_docs/fr/workplace.domain.description.md
  sdk/src/docs/models/job/recruiter_docs/fr/workplace.domain.description.md.ts
  sdk/src/docs/models/job/recruiter_docs/fr/workplace.location.description.md
  sdk/src/docs/models/job/recruiter_docs/fr/workplace.location.description.md.ts
  sdk/src/models/certification/certification.model.openapi.ts
  sdk/src/models/job/job.model.openapi.ts
  sdk/src/utils/zodWithOpenApi.ts
  server/src/jobs/importer/npec/scraper/npec.scraper.test.ts
  server/src/server/server.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/helpers/openapi/generateOpenapi.test.ts
  shared/src/helpers/openapi/generateOpenapi.ts
  shared/src/routes/job.routes.ts
  ui/app/[lang]/documentation-technique/components/redoc.tsx
  ui/app/[lang]/explorer/certifications/components/CatalogueData.tsx
  ui/app/[lang]/explorer/certifications/components/GoodToKnow.tsx
  ui/app/[lang]/explorer/certifications/page.tsx
  ui/app/i18n/settings.ts
Labels: ignore-for-release

#181 fix: be more specific on lba error
  server/src/services/apis/lba/lba.api.test.ts
  server/src/services/apis/lba/lba.api.ts
Labels: ignore-for-release

#182 fix: sentry fastify integration
  server/package.json
  server/src/services/sentry/sentry.ts
  yarn.lock
Labels: ignore-for-release

#183 feat: support de la langue sur la doc des erreurs
  sdk/src/models/errors/errors.model.openapi.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/helpers/openapi/generateOpenapi.ts
Labels: ignore-for-release

#184 fix: language redirection for auth pages
  ui/middleware.ts
  ui/utils/routes.utils.test.ts
  ui/utils/routes.utils.ts
Labels: ignore-for-release

#185 fix: switch language
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/helpers/openapi/generateOpenapi.ts
  ui/app/[lang]/documentation-technique/components/redoc.tsx
  ui/app/[lang]/documentation-technique/try/page.tsx
  ui/app/i18n/StartIntl.tsx
  ui/app/i18n/index.ts
  ui/app/i18n/locales/en/documentation-technique.json
  ui/app/i18n/locales/fr/documentation-technique.json
  ui/app/i18n/settings.ts
  ui/components/header/Header.tsx
  ui/middleware.ts
Labels: ignore-for-release

#186 [AA-542] fix: suppression d'un jeton api
  .talismanrc
  .yarn/patches/exceljs-npm-4.4.0-15bcfdd142.patch
  package.json
  server/src/services/excel/excel.parser.test.ts
  server/src/services/excel/excel.parser.ts
  ui/.eslintrc.json
  ui/app/[lang]/auth/inscription/page.tsx
  ui/app/[lang]/compte/profil/components/ApiKeyAction.tsx
  ui/app/[lang]/explorer/simulateur-npec/components/PeriodeSection.tsx
  ui/components/header/Header.tsx
  ui/components/header/MonCompteQuickAccess.tsx
  ui/components/login/withAuth.tsx
  ui/components/select/AutocompleteSelect.tsx
  yarn.lock
Labels: ignore-for-release

#187 [aa-550] re-import des collections avec mauvais encoding utf-8
  server/src/jobs/importer/dares/ape_idcc/dares.ape_idcc.importer.ts
  server/src/migrations/20240924074628-utf-8-validation.ts
Labels: ignore-for-release

#188 fix: disable sentry default fastify error handler
  server/src/services/sentry/sentry.ts
Labels: ignore-for-release

#189 fix: inscription
  ui/middleware.ts
Labels: ignore-for-release

#191 fix: utf-8 validation error
  server/src/services/mongodb/mongodbService.ts
Labels: ignore-for-release

#190 fix: tile artwork
  ui/app/[lang]/explorer/page.tsx
  ui/app/i18n/i18next.ts
  ui/app/i18n/locales/en/explorer.json
  ui/app/i18n/locales/fr/documentation-technique.json
  ui/app/i18n/locales/fr/explorer.json
  ui/app/i18n/settings.ts
  ui/components/artwork/Artwork.tsx
  ui/public/asset/artwork/book.svg
  ui/public/asset/artwork/human-cooperation.svg
  ui/public/asset/artwork/school.svg
  ui/public/asset/logo/la_bonne_alternance.png
  ui/types/svg.d.ts
Labels: ignore-for-release

#192 feat: add translations to title
  ui/app/[lang]/accessibilite/components/Accessibilite.tsx
  ui/app/[lang]/accessibilite/page.tsx
  ui/app/[lang]/admin/organisations/[id]/components/OrganisationView.tsx
  ui/app/[lang]/admin/organisations/[id]/page.tsx
  ui/app/[lang]/admin/organisations/page.tsx
  ui/app/[lang]/admin/processeur/cron/[name]/[id]/page.tsx
  ui/app/[lang]/admin/processeur/cron/[name]/page.tsx
  ui/app/[lang]/admin/processeur/job/[name]/[id]/page.tsx
  ui/app/[lang]/admin/processeur/job/[name]/page.tsx
  ui/app/[lang]/admin/processeur/page.tsx
  ui/app/[lang]/admin/utilisateurs/[id]/components/UserView.tsx
  ui/app/[lang]/admin/utilisateurs/[id]/page.tsx
  ui/app/[lang]/admin/utilisateurs/page.tsx
  ui/app/[lang]/cgu/page.tsx
  ui/app/[lang]/documentation-technique/try/page.tsx
  ui/app/[lang]/donnees-personnelles/page.tsx
  ui/app/[lang]/explorer/certifications/components/CatalogueDonneeHeadline.tsx
  ui/app/[lang]/explorer/certifications/page.tsx
  ui/app/[lang]/explorer/page.tsx
  ui/app/[lang]/explorer/simulateur-npec/page.tsx
  ui/app/[lang]/layout.tsx
  ui/app/[lang]/mentions-legales/page.tsx
  ui/app/[lang]/politique-confidentialite/page.tsx
  ui/app/i18n/index.ts
  ui/app/i18n/locales/en/global.json
  ui/app/i18n/locales/fr/global.json
  ui/app/i18n/settings.ts
  ui/components/Footer.tsx
  ui/components/breadcrumb/Breadcrumb.tsx
  ui/components/header/Header.tsx
  ui/components/header/header.utils.ts
  ui/utils/routes.utils.ts
Labels: ignore-for-release

#194 fix: lang param validation
  server/src/services/excel/excel.parser.test.ts
  ui/app/[lang]/layout.tsx
  ui/robots.ts
Labels: ignore-for-release

#196 feat(ui): ajout warning utilisation données LBA
  ui/app/[lang]/explorer/components/CatalogueHeadline.tsx
  ui/app/[lang]/explorer/recherche-offre/page.tsx
  ui/app/i18n/locales/en/explorer.json
  ui/app/i18n/locales/fr/explorer.json
Labels: documentation

#197 feat(ui): ajout traduction fr infos bulles ROME & Candidature
  sdk/src/docs/models/job/offer_read.model.doc.ts
  sdk/src/docs/models/job/offer_write.model.doc.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: documentation
