Repository mission-apprentissage/api-apprentissage, pull requests merged in 2024-11, with the labels that each got.

#221 chore: remove docker compose version
  .bin/scripts/run-playbook.sh
  .infra/docker-compose.preview-system.yml
  .infra/docker-compose.preview.yml
  .infra/docker-compose.production.yml
  .infra/docker-compose.recette.yml
Labels: ignore-for-release

#222 chore: decommission de l'environnement de preview
  .github/workflows/deploy_preview.yml
  .github/workflows/preview_cleanup.yml
  .github/workflows/pull_request.yml
  .infra/env.ini
Labels: ignore-for-release

#224 chore: update metabase connection string
  .infra/vault/vault.yml
Labels: ignore-for-release

#225 fix: increase lba timeout
  .talismanrc
  sdk/src/docs/models/job/offer_read.model.doc.ts
  server/package.json
  server/src/services/apis/lba/lba.api.test.ts
  server/src/services/apis/lba/lba.api.ts
  shared/package.json
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  ui/package.json
  yarn.lock
Labels: ignore-for-release

#226 feat: increase api key ttl to 1 year
  server/src/actions/users.actions.ts
  server/src/config.ts
  server/src/server/routes/_private/user.route.test.ts
  server/src/services/security/authenticationService.test.ts
  ui/app/[lang]/compte/profil/page.tsx
Labels: ignore-for-release

#228 chore: add more error context
  server/src/services/apis/entreprise/entreprise.ts
  server/src/services/apis/insee/insee.ts
Labels: ignore-for-release

#227 fix: npec importer on removed resources
  server/src/jobs/importer/npec/npec.importer.test.ts
  server/src/jobs/importer/npec/npec.importer.ts
  shared/src/models/source/npec/source.npec.normalized.model.ts
Labels: ignore-for-release

#229 feat!: suppression du job module
  sdk/README.md
  sdk/src/client/client.ts
  sdk/src/client/internal/job/__snapshots__/job.module.test.ts.snap
  sdk/src/client/internal/job/job.module.test.ts
  sdk/src/client/internal/job/job.module.ts
Labels: breaking-change

#230 fix: support des habilitations à venir par la methode parseAccessToken
  sdk/src/jwt/jwtAuthToken.ts
Labels: bug

#231 feat: passe plat de l'api La bonne alternance
  .talismanrc
  sdk/package.json
  sdk/src/external/internal.ts
  sdk/src/external/laBonneAlternance.api.test.ts
  sdk/src/external/laBonneAlternance.api.ts
  sdk/src/internal.ts
  sdk/src/models/index.ts
  sdk/src/models/job/index.ts
  sdk/src/models/job/internal.ts
  sdk/src/models/job/job.model.test.ts
  sdk/src/models/job/job.model.ts
  sdk/src/models/job/job.primitives.ts
  sdk/src/routes/common.routes.ts
  sdk/src/routes/jobs/job.routes.ts
  server/package.json
  server/src/commands.ts
  server/src/server/routes/job/job.route.test.ts
  server/src/server/routes/job/job.routes.ts
  server/src/services/apis/lba/lba.api.test.ts
  server/src/services/apis/lba/lba.api.ts
  server/src/services/forward/forwardApi.service.test.ts
  server/src/services/forward/forwardApi.service.ts
  server/src/services/jobs/job.service.test.ts
  server/src/services/jobs/job.service.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/helpers/openapi/generateOpenapi.test.ts
  shared/src/helpers/openapi/generateOpenapi.ts
  shared/src/routes/index.test.ts
  yarn.lock
Labels: ignore-for-release

#232 feat(server): add Kit_apprentissage_20241025
  server/static/kit_apprentissage/Kit_apprentissage_20241025.xlsx
Labels: enhancement

#234 feat: controle de la synchronisation de la documentation avec La bonne alternance
  sdk/src/models/job/job.model.openapi.ts
  sdk/src/routes/jobs/job.routes.openapi.ts
  server/package.json
  server/src/commands.ts
  server/src/jobs/jobs.ts
  server/src/services/documentation/checkDocumentationSync.ts
  server/src/services/documentation/expectedDocumentationDelta.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/helpers/openapi/compareOpenapiStructure.ts
  shared/src/helpers/openapi/generateOpenapi.test.ts
  shared/src/routes/job.routes.ts
  yarn.lock
Labels: ignore-for-release

#235 feat: ajout de la route pour postuler à une opportunité d'emploi La bonne alternance
  sdk/src/routes/jobs/job.routes.ts
  server/src/server/routes/certification.route.test.ts
  server/src/server/routes/experimental/sources/acce.routes.test.ts
  server/src/server/routes/geographie.route.test.ts
  server/src/server/routes/job/job.route.test.ts
  server/src/server/routes/job/job.routes.ts
  server/src/server/routes/organismes.routes.test.ts
  server/src/services/security/authenticationService.test.ts
  server/src/services/security/authenticationService.ts
  shared/src/routes/job.routes.ts
Labels: enhancement

#239 feat: reduce sentry profiling rate
  server/src/services/sentry/sentry.ts
Labels: ignore-for-release

#237 feat: increase mongodb pool-size
  server/src/services/mongodb/mongodbService.ts
Labels: ignore-for-release

#236 fix: delay usage request after sending response
  server/src/server/middlewares/apiKeyUsageMiddleware.test.ts
  server/src/server/middlewares/apiKeyUsageMiddleware.ts
Labels: ignore-for-release

#238 fix: improve authentication speed
  server/.env.test
  server/src/actions/users.actions.ts
  server/src/server/routes/_private/user.route.test.ts
  server/src/services/security/authenticationService.test.ts
  server/src/services/security/authenticationService.ts
  server/src/utils/jwtUtils.ts
Labels: ignore-for-release

#240 fix: delay last_used_at to onResponse hook
  server/src/server/middlewares/apiKeyUsageMiddleware.test.ts
  server/src/server/middlewares/apiKeyUsageMiddleware.ts
  server/src/services/security/authenticationService.test.ts
  server/src/services/security/authenticationService.ts
Labels: ignore-for-release

#241 fix: creation offre d'emploi
  .infra/docker-compose.production.yml
  server/src/server/routes/job/job.routes.ts
Labels: ignore-for-release

#242 fix: compare key as fallback
  server/src/services/security/authenticationService.ts
Labels: ignore-for-release

#243 feat: add cache to certification, geographie and organisme module
  sdk/package.json
  sdk/src/client/internal/certification/certification.module.test.ts
  sdk/src/client/internal/certification/certification.module.ts
  sdk/src/client/internal/geographie/geographie.module.ts
  sdk/src/client/internal/organisme/organisme.module.ts
  yarn.lock
Labels: enhancement

#244 feat: ajout de cache sur l'API entreprise
  server/package.json
  server/src/services/apis/entreprise/entreprise.ts
  yarn.lock
Labels: ignore-for-release

#247 feat: ajout des missions locales dans le referentiel commune
  .talismanrc
  sdk/src/client/internal/geographie/geographie.module.test.ts
  sdk/src/docs/models/commune/commune.model.doc.ts
  sdk/src/models/geographie/commune.model.openapi.ts
  sdk/src/models/geographie/commune.model.ts
  server/src/config.ts
  server/src/jobs/importer/commune/__snapshots__/commune.importer.test.ts.snap
  server/src/jobs/importer/commune/commune.importer.test.ts
  server/src/jobs/importer/commune/commune.importer.ts
  server/src/jobs/jobs.ts
  server/src/migrations/20241128145114-mission-locales.ts
  server/src/services/apis/unml/unml.test.ts
  server/src/services/apis/unml/unml.ts
  shared/src/apis/index.ts
  shared/src/apis/unml.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/helpers/openapi/generateOpenapi.test.ts
  shared/src/models/fixtures/commune.model.fixture.ts
Labels: enhancement

#248 fix: api-entreprise client
  server/package.json
  server/src/services/apis/entreprise/entreprise.ts
  yarn.lock
Labels: ignore-for-release

#245 chore: infra update mongodb config local
  .bin/scripts/setup-local-env.sh
  .github/workflows/ci.yml
  .infra/local/Dockerfile
  docker-compose.yml
  package.json
Labels: ignore-for-release

#249 chore: update seed
  .infra/files/configs/mongodb/seed.gpg
  .talismanrc
Labels: ignore-for-release

#250 feat: mission locale API
  .talismanrc
  sdk/src/client/internal/geographie/__snapshots__/geographie.module.test.ts.snap
  sdk/src/client/internal/geographie/geographie.module.test.ts
  sdk/src/client/internal/geographie/geographie.module.ts
  sdk/src/docs/internal.ts
  sdk/src/docs/models/commune/commune.model.doc.ts
  sdk/src/docs/models/mission-locale/mission-locale.model.doc.ts
  sdk/src/docs/routes/listMissionLocales/listMissionLocales.route.doc.ts
  sdk/src/models/geographie/commune.model.openapi.ts
  sdk/src/models/geographie/commune.model.ts
  sdk/src/models/geographie/index.ts
  sdk/src/models/geographie/internal.ts
  sdk/src/models/geographie/mission-locale.model.openapi.ts
  sdk/src/models/geographie/mission-locale.model.ts
  sdk/src/routes/geographie.routes.ts
  server/src/jobs/importer/commune/__snapshots__/commune.importer.test.ts.snap
  server/src/server/routes/geographie.route.test.ts
  server/src/server/routes/geographie.route.ts
  shared/src/apis/unml.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/helpers/openapi/generateOpenapi.ts
  shared/src/models/commune.model.ts
  shared/src/models/fixtures/commune.model.fixture.ts
  shared/src/routes/geographie.routes.ts
  ui/app/[lang]/explorer/page.tsx
  ui/app/[lang]/explorer/recuperation-mission-locales/page.tsx
  ui/app/i18n/locales/en/explorer.json
  ui/app/i18n/locales/en/global.json
  ui/app/i18n/locales/fr/explorer.json
  ui/app/i18n/locales/fr/global.json
  ui/public/asset/logo/unml.svg
  ui/utils/routes.utils.ts
Labels: enhancement
