Repository mission-apprentissage/api-apprentissage, pull requests merged in 2024-10, with the labels that each got.

#199 fix(ui): correction du titre de la doc Recherche opportunités
  ui/app/[lang]/explorer/recherche-offre/page.tsx
Labels: documentation

#200 fix: exceljs file cleanup
  .yarn/patches/exceljs-npm-4.4.0-15bcfdd142.patch
  yarn.lock
Labels: ignore-for-release

#198 fix(ui): add lang param to useCallback dependancies
  ui/components/header/MonCompteQuickAccess.tsx
Labels: enhancement

#201 feat: update du kit apprentissate (2024.09.30)
  server/static/kit_apprentissage/Kit_apprentissage_20240930.xlsx
Labels: enhancement

#202 fix: update de la regex code Rome
  sdk/src/models/certification/certification.model.openapi.ts
  sdk/src/models/certification/certification.primitives.ts
  server/src/jobs/importer/bcn/bcn.importer.ts
  server/src/jobs/importer/certifications/certifications.importer.ts
  server/src/jobs/importer/dares/ape_idcc/dares.ape_idcc.importer.ts
  server/src/jobs/importer/dares/ape_idcc/scraper/dares.ape_idcc.scraper.ts
  server/src/jobs/importer/dares/ccn/dares.ccn.importer.ts
  server/src/jobs/importer/dares/ccn/scraper/dares.ccn.scraper.ts
  server/src/jobs/importer/france_competence/france_competence.importer.ts
  server/src/jobs/importer/kali/kali.ccn.importer.ts
  server/src/jobs/importer/kit/kitApprentissage.importer.ts
  server/src/jobs/importer/npec/normalizer/npec.normalizer.ts
  server/src/jobs/importer/npec/npec.importer.ts
  server/src/services/errors/withCause.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: bug

#204 feat: import referentiel communes
  .infra/.env_server
  .infra/vault/vault.yml
  sdk/src/models/index.ts
  sdk/src/models/territoire/commune.model.ts
  sdk/src/models/territoire/departement.model.ts
  sdk/src/models/territoire/geoJson.model.ts
  sdk/src/models/territoire/index.ts
  sdk/src/models/territoire/region.model.ts
  server/.env.test
  server/package.json
  server/src/config.ts
  server/src/jobs/importer/commune/__snapshots__/commune.importer.test.ts.snap
  server/src/jobs/importer/commune/commune.importer.test.ts
  server/src/jobs/importer/commune/commune.importer.ts
  server/src/jobs/jobs.ts
  server/src/services/apis/geo/geo.test.ts
  server/src/services/apis/geo/geo.ts
  server/src/services/apis/insee/insee.test.ts
  server/src/services/apis/insee/insee.ts
  shared/package.json
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/commune.model.ts
  shared/src/models/import.meta.model.ts
  shared/src/models/models.ts
  ui/package.json
  yarn.lock
Labels: enhancement

#205 feat: import des academies
  sdk/src/models/territoire/departement.model.ts
  server/src/config.ts
  server/src/jobs/importer/commune/__snapshots__/commune.importer.test.ts.snap
  server/src/jobs/importer/commune/commune.importer.test.ts
  server/src/jobs/importer/commune/commune.importer.ts
  server/src/migrations/20241008164612-referentiel-commune.ts
  server/src/services/apis/enseignementSup/enseignementSup.test.ts
  server/src/services/apis/enseignementSup/enseignementSup.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  ui/app/[lang]/documentation-technique/components/redoc.tsx
  ui/hooks/useJwtToken.ts
Labels: ignore-for-release

#206 fix(ui): titre liste des certifications
  ui/app/[lang]/explorer/certifications/page.tsx
Labels: ignore-for-release

#209 chore: upgrade deps
  .talismanrc
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarnrc.yml
  package.json
  sdk/package.json
  server/.eslintrc.json
  server/package.json
  server/src/server/middlewares/errorMiddleware.ts
  server/src/services/mailer/mailer.ts
  shared/package.json
  ui/package.json
  yarn.lock
Labels: ignore-for-release

#210 fix: dares importer
  .talismanrc
  server/src/jobs/importer/dares/ccn/dares.ccn.importer.test.ts
  server/src/jobs/importer/dares/ccn/fixtures/article.html
  server/src/jobs/importer/dares/ccn/scraper/dares.ccn.scraper.test.ts
  server/src/jobs/importer/dares/ccn/scraper/dares.ccn.scraper.ts
Labels: ignore-for-release

#208 breaking-change: lbac 1501: mise à jour du modele adresse lba
  sdk/src/external/laBonneAlternance.api.test.ts
  sdk/src/external/laBonneAlternance.api.ts
  server/src/server/routes/job/job.route.test.ts
  server/src/services/apis/lba/lba.api.test.ts
  server/src/services/jobs/job.service.test.ts
  server/src/services/jobs/job.service.ts
Labels: ignore-for-release

#213 feat: export de zUai & zSiret pour la validation respective de l'Uai et du Siret
  sdk/src/models/organisme/index.ts
Labels: enhancement

#216 feat(sdk): update api habilitations
  sdk/src/jwt/jwtAuthToken.ts
  server/src/services/apis/lba/lba.api.test.ts
  server/src/services/apis/lba/lba.api.ts
  server/src/services/security/authorisationService.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/organisation.model.ts
  shared/src/security/permissions.ts
  ui/app/[lang]/admin/organisations/[id]/components/OrganisationView.tsx
Labels: enhancement

#217 chore: add kevin access
  .infra/vault/vault.yml
Labels: ignore-for-release
