Repository mission-apprentissage/api-apprentissage, pull requests merged in 2024-12, with the labels that each got.

#252 feat: update documentation
  docs/developpement/1password.md
  docs/developpement/developpement.md
  docs/developpement/pre-requesites.md
  ui/middleware.ts
Labels: documentation

#253 fix: mise à jour de l'url de l'API BCN
  server/src/services/apis/bcn/bcn.test.ts
  server/src/services/apis/bcn/bcn.ts
Labels: ignore-for-release

#254 feat: definition du date de fin d'enregistrement majorée
  server/src/jobs/importer/certifications/builder/periode_validite/certification.periode_validite.builder.test.ts
  server/src/jobs/importer/certifications/builder/periode_validite/certification.periode_validite.builder.ts
Labels: ignore-for-release

#246 feat: fix job object
  sdk/src/docs/models/job/offer_read.model.doc.ts
  sdk/src/models/job/job.model.openapi.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: bug

#255 wip: put job content JSON
  server/src/server/routes/job/job.routes.ts
Labels: ignore-for-release

#259 fix: correction du control de synchronisation de doc & refactor
  server/src/jobs/jobs.ts
  server/src/services/documentation/checkDocumentationSync.ts
  server/src/services/documentation/expectedDocumentationDelta.ts
  shared/src/helpers/openapi/compareOpenapiStructure.ts
Labels: ignore-for-release

#262 chore: utilisation de docker pour exécuter ansible en local
  .bin/scripts/setup-local-env.sh
Labels: ignore-for-release

#256 feat(infra): update du JWT Secret local
  .infra/vault/vault.yml
Labels: ignore-for-release

#264 feat(infra): remove mailpit & replace with SMTP host for recette env
  .infra/docker-compose.recette.yml
  .infra/vault/vault.yml
Labels: ignore-for-release

#263 feat(infra): update du vault pour l'env local
  .infra/vault/vault.yml
Labels: ignore-for-release

#261 feat(server): fix ACCE url
  server/src/services/apis/acce/acce.test.ts
  server/src/services/apis/acce/acce.ts
Labels: bug

#265 fix(server): fix de l'import du Kit Apprentissage & update version de novembre
  server/src/jobs/importer/kit/builder/kit_apprentissage.builder.ts
  server/static/kit_apprentissage/Kit_apprentissage_20241025.xlsx
  server/static/kit_apprentissage/Kit_apprentissage_20241129.xlsx
Labels: bug

#266 feat: construction du model Organisme
  sdk/src/models/organisme/organisme.model.ts
  sdk/src/routes/organisme.routes.ts
  server/package.json
  server/src/jobs/importer/organisme/builder/organisme.builder.ts
  server/src/jobs/importer/organisme/organisme.importer.fixtures.ts
  server/src/jobs/importer/organisme/organisme.importer.test.ts
  server/src/jobs/importer/organisme/organisme.importer.ts
  server/src/jobs/importer/referentiel/referentiel.ts
  server/src/jobs/jobs.ts
  server/src/services/apis/entreprise/entreprise.test.ts
  server/src/services/apis/entreprise/entreprise.ts
  server/src/services/apis/entreprise/rechercheEntreprise.ts
  server/src/services/apis/entreprise/tmp/adresseUtils.ts
  server/src/services/apis/entreprise/tmp/infoSiret.actions-struct.d.ts
  server/src/services/apis/entreprise/tmp/infoSiret.actions.ts
  server/src/services/apis/referentiel/referentiel.test.ts
  server/src/services/apis/referentiel/referentiel.ts
  shared/package.json
  shared/src/helpers/common.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/cache/cache.entreprise.model.ts
  shared/src/models/import.meta.model.ts
  shared/src/models/models.ts
  shared/src/models/organisme.model.ts
  yarn.lock
Labels: ignore-for-release

#267 fix: recette deployment
  .infra/ansible/tasks/files_copy.yml
  .infra/docker-compose.recette.yml
Labels: ignore-for-release

#258 feat: add offer status to open api definition
  docs/developpement/developpement.md
  package.json
  sdk/package.json
  sdk/src/models/job/job.model.openapi.ts
  server/package.json
  server/src/jobs/importer/npec/scraper/npec.scraper.test.ts
  shared/package.json
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  ui/package.json
  yarn.lock
Labels: ignore-for-release

#260 feat(ui): traduction des composants utilisateurs
  ui/app/[lang]/auth/inscription/page.tsx
  ui/app/[lang]/compte/profil/components/ApiKeyAction.tsx
  ui/app/[lang]/compte/profil/components/GenerateApiKey.tsx
  ui/app/[lang]/compte/profil/components/ManageApiKeysBanner.tsx
  ui/app/[lang]/compte/profil/page.tsx
  ui/app/i18n/i18next.ts
  ui/app/i18n/locales/en/global.json
  ui/app/i18n/locales/en/inscription-connexion.json
  ui/app/i18n/locales/fr/global.json
  ui/app/i18n/locales/fr/inscription-connexion.json
  ui/app/i18n/settings.ts
  ui/components/header/Header.tsx
  ui/components/header/MonCompteQuickAccess.tsx
  ui/components/login/LoginEmailSent.tsx
  ui/components/login/LoginModal.tsx
  ui/utils/routes.utils.test.ts
Labels: ignore-for-release

#269 feat: import catalogue restreint au réglementaire publique
  .talismanrc
  server/src/jobs/importer/catalogue/catalogue.importer.test.ts
  server/src/jobs/importer/catalogue/catalogue.importer.ts
  server/src/jobs/importer/catalogue/fixtures/sample.ts
  server/src/services/apis/catalogue/__snapshots__/catalogue.test.ts.snap
  server/src/services/apis/catalogue/catalogue.test.ts
  server/src/services/apis/catalogue/catalogue.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/import.meta.model.ts
  shared/src/models/source/catalogue/source.catalogue.model.ts
Labels: ignore-for-release
