Repository mission-apprentissage/api-apprentissage, pull requests merged in 2025-03, with the labels that each got.

#362 fix: upgrade deps
  .github/workflows/ci.yml
  package.json
  sdk/package.json
  server/package.json
  server/src/jobs/importer/dares/ape_idcc/fixtures/article.html
  server/src/services/documentation/checkDocumentationSync.ts
  server/src/services/forward/forwardApi.service.test.ts
  server/src/services/forward/forwardApi.service.ts
  server/src/services/mailer/mailer.ts
  shared/package.json
  ui/package.json
  yarn.lock
Labels: bug

#363 fix: job processor oom
  .infra/docker-compose.production.yml
  server/src/jobs/importer/france_competence/france_competence.importer.ts
Labels: bug

#359 feat: update & correction du wording docs métiers
  sdk/src/docs/metier/certifications/fr/intitule.description.md
  sdk/src/docs/metier/certifications/fr/intitule.description.md.ts
  sdk/src/docs/metier/generation-lien-prise-rdv-formation/generation-lien-prise-rdv-formation.doc.ts
  sdk/src/docs/metier/recherche-formation/recherche-formation.doc.ts
Labels: documentation

#361 feat: remove simulateur
  ui/app/[lang]/explorer/page.tsx
  ui/app/[lang]/explorer/simulateur-npec/components/CertificationSection.tsx
  ui/app/[lang]/explorer/simulateur-npec/components/EntrepriseSection.tsx
  ui/app/[lang]/explorer/simulateur-npec/components/Pastille.tsx
  ui/app/[lang]/explorer/simulateur-npec/components/PeriodeSection.tsx
  ui/app/[lang]/explorer/simulateur-npec/components/ResultSection.tsx
  ui/app/[lang]/explorer/simulateur-npec/components/SimulateurNpecContrat.tsx
  ui/app/[lang]/explorer/simulateur-npec/components/SimulateurNpecHeadline.tsx
  ui/app/[lang]/explorer/simulateur-npec/page.tsx
  ui/app/i18n/locales/en/explorer.json
  ui/app/i18n/locales/en/global.json
  ui/app/i18n/locales/fr/explorer.json
  ui/app/i18n/locales/fr/global.json
  ui/utils/routes.utils.ts
Labels: enhancement

#364 fix: docker file syntax warning
  Dockerfile
Labels: enhancement

#365 feature : downgrade NextJs to 15.1.4
  ui/package.json
  yarn.lock
Labels: dependencies

#366 fix: kit apprentissage timeout
  server/src/services/apis/kit_apprentissage/kit_apprentissage.api.ts
  ui/middleware.ts
  ui/next.config.mjs
Labels: bug

#367 fix: france competence stale import
  server/src/jobs/importer/france_competence/france_competence.importer.ts
Labels: bug

#369 feat: fix wording & logo
  sdk/src/docs/metier/generation-lien-prise-rdv-formation/generation-lien-prise-rdv-formation.doc.ts
  sdk/src/docs/routes/generateFormationAppointmentLink/generateFormationAppointmentLink.doc.ts
Labels: enhancement

#368 feat: ajout de la route de récupération d'une offre d'emploi en alternance
  .talismanrc
  sdk/src/docs/metier/internal.ts
  sdk/src/docs/metier/recuperation-detail-offre/en/apply.description.md
  sdk/src/docs/metier/recuperation-detail-offre/en/apply.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/en/contract.description.md
  sdk/src/docs/metier/recuperation-detail-offre/en/contract.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/en/description.md
  sdk/src/docs/metier/recuperation-detail-offre/en/description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/en/identifier.description.md
  sdk/src/docs/metier/recuperation-detail-offre/en/identifier.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/en/offer.description.md
  sdk/src/docs/metier/recuperation-detail-offre/en/offer.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/en/offer.publication.description.md
  sdk/src/docs/metier/recuperation-detail-offre/en/offer.publication.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/en/offer.status.description.md
  sdk/src/docs/metier/recuperation-detail-offre/en/offer.status.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/en/workplace.description.md
  sdk/src/docs/metier/recuperation-detail-offre/en/workplace.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/en/workplace.domain.description.md
  sdk/src/docs/metier/recuperation-detail-offre/en/workplace.domain.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/en/workplace.location.description.md
  sdk/src/docs/metier/recuperation-detail-offre/en/workplace.location.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/fr/apply.description.md
  sdk/src/docs/metier/recuperation-detail-offre/fr/apply.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/fr/contract.description.md
  sdk/src/docs/metier/recuperation-detail-offre/fr/contract.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/fr/description.md
  sdk/src/docs/metier/recuperation-detail-offre/fr/description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/fr/identifier.description.md
  sdk/src/docs/metier/recuperation-detail-offre/fr/identifier.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/fr/offer.description.md
  sdk/src/docs/metier/recuperation-detail-offre/fr/offer.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/fr/offer.publication.description.md
  sdk/src/docs/metier/recuperation-detail-offre/fr/offer.publication.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/fr/offer.status.description.md
  sdk/src/docs/metier/recuperation-detail-offre/fr/offer.status.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/fr/workplace.description.md
  sdk/src/docs/metier/recuperation-detail-offre/fr/workplace.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/fr/workplace.domain.description.md
  sdk/src/docs/metier/recuperation-detail-offre/fr/workplace.domain.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/fr/workplace.location.description.md
  sdk/src/docs/metier/recuperation-detail-offre/fr/workplace.location.description.md.ts
  sdk/src/docs/metier/recuperation-detail-offre/recuperation-detail-offre.doc.ts
  sdk/src/docs/routes/jobSearchById/jobSearchById.route.doc.ts
  sdk/src/routes/jobs/job.routes.openapi.ts
  sdk/src/routes/jobs/job.routes.ts
  server/src/server/routes/job/job.route.test.ts
  server/src/server/routes/job/job.routes.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
  ui/app/[lang]/explorer/page.tsx
  ui/app/[lang]/explorer/recuperation-detail-offre/page.tsx
  ui/utils/routes.utils.ts
Labels: enhancement

#374 feat: fix wordings & url
  sdk/src/docs/metier/recherche-formation/recherche-formation.doc.ts
Labels: documentation

#336 feat: modification du branding API en Espace développeurs
  sdk/src/openapi/builder/openapi.builder.ts
  sdk/src/openapi/utils/openapi.uils.ts
  server/src/server/routes/healthcheck.routes.ts
  server/src/services/mailer/mailer.ts
  server/static/emails/common/footer.ejs
  server/static/emails/common/head.ejs
  server/static/emails/common/signature.ejs
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
  ui/app/[lang]/auth/refus-inscription/page.tsx
  ui/app/[lang]/cgu/components/Cgu.tsx
  ui/app/[lang]/layout.tsx
  ui/app/[lang]/mentions-legales/components/MentionLegales.tsx
  ui/app/[lang]/page.tsx
  ui/app/[lang]/politique-confidentialite/components/PolitiqueConfidentialite.tsx
  ui/app/i18n/locales/en/inscription-connexion.json
  ui/app/i18n/locales/fr/explorer.json
  ui/app/i18n/locales/fr/global.json
  ui/app/i18n/locales/fr/inscription-connexion.json
  ui/components/header/Header.tsx
  ui/config.public.ts
  ui/public/images/logo_LBA.svg
Labels: ignore-for-release

#370 feat: ajout info dépot cfa
  sdk/src/docs/metier/depot-offre/depot-offre.doc.ts
Labels: documentation

#375 fix: markdown
  sdk/src/docs/metier/depot-offre/depot-offre.doc.ts
Labels: documentation

#377 fix: wording API Apprentissage
  ui/app/[lang]/cgu/components/Cgu.tsx
Labels: enhancement

#376 fix: doc de la route getJobById
  sdk/src/routes/jobs/job.routes.openapi.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: bug

#378 feat: remove bold
  .talismanrc
  sdk/src/docs/metier/depot-offre/depot-offre.doc.ts
Labels: enhancement

#379 feat:update cgu last date
  ui/app/[lang]/cgu/components/Cgu.tsx
Labels: enhancement
