Repository mission-apprentissage/api-apprentissage, pull requests merged in 2025-06, with the labels that each got.

#394 feat: add department & opco as search input parameter
  sdk/src/docs/routes/jobSearch/en/parameters/department.md
  sdk/src/docs/routes/jobSearch/en/parameters/department.md.ts
  sdk/src/docs/routes/jobSearch/en/parameters/latitude.md
  sdk/src/docs/routes/jobSearch/en/parameters/latitude.md.ts
  sdk/src/docs/routes/jobSearch/en/parameters/longitude.md
  sdk/src/docs/routes/jobSearch/en/parameters/longitude.md.ts
  sdk/src/docs/routes/jobSearch/en/parameters/opco.md
  sdk/src/docs/routes/jobSearch/en/parameters/opco.md.ts
  sdk/src/docs/routes/jobSearch/en/parameters/radius.md
  sdk/src/docs/routes/jobSearch/en/parameters/radius.md.ts
  sdk/src/docs/routes/jobSearch/en/parameters/rncp.md
  sdk/src/docs/routes/jobSearch/en/parameters/rncp.md.ts
  sdk/src/docs/routes/jobSearch/en/parameters/romes.md
  sdk/src/docs/routes/jobSearch/en/parameters/romes.md.ts
  sdk/src/docs/routes/jobSearch/en/parameters/target_diploma_level.md
  sdk/src/docs/routes/jobSearch/en/parameters/target_diploma_level.md.ts
  sdk/src/docs/routes/jobSearch/en/response/jobs.md
  sdk/src/docs/routes/jobSearch/en/response/jobs.md.ts
  sdk/src/docs/routes/jobSearch/en/response/recruiters.md
  sdk/src/docs/routes/jobSearch/en/response/recruiters.md.ts
  sdk/src/docs/routes/jobSearch/en/response/warnings.md
  sdk/src/docs/routes/jobSearch/en/response/warnings.md.ts
  sdk/src/docs/routes/jobSearch/fr/parameters/department.md
  sdk/src/docs/routes/jobSearch/fr/parameters/department.md.ts
  sdk/src/docs/routes/jobSearch/fr/parameters/latitude.md
  sdk/src/docs/routes/jobSearch/fr/parameters/latitude.md.ts
  sdk/src/docs/routes/jobSearch/fr/parameters/longitude.md
  sdk/src/docs/routes/jobSearch/fr/parameters/longitude.md.ts
  sdk/src/docs/routes/jobSearch/fr/parameters/opco.md
  sdk/src/docs/routes/jobSearch/fr/parameters/opco.md.ts
  sdk/src/docs/routes/jobSearch/fr/parameters/radius.md
  sdk/src/docs/routes/jobSearch/fr/parameters/radius.md.ts
  sdk/src/docs/routes/jobSearch/fr/parameters/rncp.md
  sdk/src/docs/routes/jobSearch/fr/parameters/rncp.md.ts
  sdk/src/docs/routes/jobSearch/fr/parameters/romes.md
  sdk/src/docs/routes/jobSearch/fr/parameters/romes.md.ts
  sdk/src/docs/routes/jobSearch/fr/parameters/target_diploma_level.md
  sdk/src/docs/routes/jobSearch/fr/parameters/target_diploma_level.md.ts
  sdk/src/docs/routes/jobSearch/fr/response/jobs.md
  sdk/src/docs/routes/jobSearch/fr/response/jobs.md.ts
  sdk/src/docs/routes/jobSearch/fr/response/recruiters.md
  sdk/src/docs/routes/jobSearch/fr/response/recruiters.md.ts
  sdk/src/docs/routes/jobSearch/fr/response/warnings.md
  sdk/src/docs/routes/jobSearch/fr/response/warnings.md.ts
  sdk/src/docs/routes/jobSearch/jobSearch.route.doc.ts
  sdk/src/docs/routes/jobSearch/response/warnings.md
  sdk/src/docs/routes/jobSearch/response/warnings.md.ts
  sdk/src/routes/jobs/job.routes.openapi.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: enhancement

#395 feat(lbac-2749): implementation de la route /job/v1/offer/:id/publishing-informations
  .talismanrc
  sdk/src/docs/models/job/JobOfferPublishing.doc.ts
  sdk/src/docs/routes/jobSearchById/jobSearchById.route.doc.ts
  sdk/src/models/job/job.publishing.model.openapi.ts
  sdk/src/openapi/openapiSpec.ts
  sdk/src/routes/jobs/job.routes.openapi.ts
  sdk/src/routes/jobs/job.routes.ts
  server/src/server/routes/job/job.routes.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: enhancement

#396 fix: api param naming
  sdk/src/docs/routes/jobSearch/fr/parameters/departements.md
  sdk/src/docs/routes/jobSearch/fr/parameters/departements.md.ts
  sdk/src/docs/routes/jobSearch/jobSearch.route.doc.ts
  sdk/src/routes/jobs/job.routes.openapi.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: bug

#397 fix: route doc
  sdk/src/docs/routes/jobSearch/jobSearch.route.doc.ts
  sdk/src/routes/jobs/job.routes.openapi.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: documentation

#398 chore: update minor deps
  package.json
  sdk/package.json
  sdk/src/models/organisme/organismes.primitives.test.ts
  server/package.json
  shared/package.json
  ui/package.json
  yarn.lock
Labels: dependencies

#403 chore: reduce seed
  .infra/files/configs/mongodb/seed.gpg
Labels: ignore-for-release

#404 feat: replace jsonwebtoken by jose
  .talismanrc
  docker-compose.yml
  eslint.config.mjs
  sdk/package.json
  sdk/src/.eslintrc.json
  sdk/src/jwt/jwtAuthToken.ts
  server/package.json
  server/src/actions/auth.actions.ts
  server/src/actions/sessions.actions.ts
  server/src/actions/users.actions.ts
  server/src/commands.ts
  server/src/config.ts
  server/src/index.ts
  server/src/main.ts
  server/src/migrations/20240319112656-certification-model.ts
  server/src/server/routes/_private/auth.route.test.ts
  server/src/server/routes/_private/user.route.test.ts
  server/src/server/routes/formations/formations.route.test.ts
  server/src/server/routes/job/job.route.test.ts
  server/src/services/forward/forwardApi.service.test.ts
  server/src/services/forward/forwardApi.service.ts
  server/src/services/mailer/mailer.ts
  server/src/services/security/accessTokenService.test.ts
  server/src/services/security/accessTokenService.ts
  server/src/services/security/authenticationService.test.ts
  server/src/services/security/authenticationService.ts
  server/src/services/security/authorisationService.test.ts
  server/src/utils/jwtUtils.ts
  shared/src/models/user.model.ts
  ui/app/[lang]/admin/hooks/useDeleteOrganisation.ts
  ui/app/[lang]/admin/organisations/[id]/components/OrganisationView.tsx
  ui/app/i18n/StartIntl.tsx
  vitest.config.ts
  vitest.workspace.ts
  yarn.lock
Labels: breaking-change
