Repository mission-apprentissage/api-apprentissage, pull requests merged in 2025-04, with the labels that each got.

#380 fix: unml mapping
  .infra/files/configs/mongodb/seed.gpg
  .talismanrc
  server/src/jobs/importer/mission_locale/mission_locale.importer.ts
Labels: ignore-for-release

#383 feat: reorder doc
  sdk/src/docs/routes/generateFormationAppointmentLink/generateFormationAppointmentLink.doc.ts
  sdk/src/routes/formation/formation.routes.openapi.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: documentation

#384 fix: logo lba
  sdk/src/docs/metier/generation-lien-prise-rdv-formation/generation-lien-prise-rdv-formation.doc.ts
Labels: enhancement

#386 fix: update api entreprise API key
  .infra/vault/vault.yml
  .talismanrc
  server/package.json
  server/src/services/apis/entreprise/entreprise.ts
  server/src/services/apis/geo/geo.ts
  shared/package.json
  ui/package.json
  yarn.lock
Labels: ignore-for-release
