Repository mission-apprentissage/api-apprentissage, pull requests merged in 2025-01, with the labels that each got.

#271 feat: update lba api documentation
  sdk/src/docs/models/job/application.model.doc.ts
  sdk/src/docs/models/job/offer_write.model.doc.ts
  sdk/src/docs/models/job/recruiter.model.doc.ts
  sdk/src/models/job/job.model.openapi.ts
  server/src/services/documentation/checkDocumentationSync.ts
  server/src/services/documentation/expectedDocumentationDelta.ts
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  ui/app/[lang]/explorer/candidature-offre/page.tsx
  ui/app/i18n/locales/en/explorer.json
  ui/app/i18n/locales/fr/explorer.json
Labels: ignore-for-release

#272 feat: ajout des arrondissements et anciennes communes fusionnées
  sdk/src/client/internal/geographie/geographie.module.test.ts
  sdk/src/docs/models/commune/commune.model.doc.ts
  sdk/src/models/geographie/commune.model.openapi.ts
  sdk/src/models/geographie/commune.model.ts
  sdk/src/utils/zodWithOpenApi.ts
  server/src/jobs/importer/commune/__snapshots__/commune.importer.test.ts.snap
  server/src/jobs/importer/commune/commune.importer.test.ts
  server/src/jobs/importer/commune/commune.importer.ts
  server/src/jobs/importer/organisme/organisme.importer.fixtures.ts
  server/src/migrations/20241008164612-referentiel-commune.ts
  server/src/migrations/20241010164812-geographie-api.ts
  server/src/migrations/20241017075143-import-communes.ts
  server/src/migrations/20250102153339-commune.ts
  server/src/services/apis/insee/insee.test.ts
  server/src/services/apis/insee/insee.ts
  shared/src/apis/insee.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/helpers/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/models/commune.model.ts
  shared/src/models/fixtures/commune.model.fixture.ts
Labels: enhancement

#273 feat: récupération des formations du catalogue générale des campagnes précedentes
  server/src/jobs/importer/catalogue/catalogue.importer.ts
  server/src/jobs/importer/catalogue/fixtures/sample.ts
  server/src/migrations/20250103130705-catalogue.ts
  server/src/services/apis/catalogue/__snapshots__/catalogue.test.ts.snap
  server/src/services/apis/catalogue/catalogue.test.ts
  server/src/services/apis/catalogue/catalogue.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/source/catalogue/source.catalogue.model.ts
Labels: ignore-for-release

#275 fix: france competence import race condition
  server/src/jobs/importer/certifications/certifications.importer.ts
  server/src/jobs/importer/france_competence/france_competence.importer.ts
Labels: ignore-for-release

#277 feat: import formations du catalogue
  .talismanrc
  sdk/src/models/certification/certification.primitives.ts
  sdk/src/models/formation/formation.model.openapi.ts
  sdk/src/models/formation/formation.model.ts
  sdk/src/models/formation/index.ts
  sdk/src/models/formation/internal.ts
  sdk/src/models/index.ts
  sdk/src/models/internal.ts
  server/package.json
  server/src/jobs/importer/formation/builder/_.formation.builder.test.ts
  server/src/jobs/importer/formation/builder/_.formation.builder.ts
  server/src/jobs/importer/formation/builder/__snapshots__/certification.formation.builder.test.ts.snap
  server/src/jobs/importer/formation/builder/certification.formation.builder.test.ts
  server/src/jobs/importer/formation/builder/certification.formation.builder.ts
  server/src/jobs/importer/formation/builder/lieu.formation.builder.test.ts
  server/src/jobs/importer/formation/builder/lieu.formation.builder.ts
  server/src/jobs/importer/formation/builder/modalite.formation.builder.test.ts
  server/src/jobs/importer/formation/builder/modalite.formation.builder.ts
  server/src/jobs/importer/formation/builder/organisme.formation.builder.test.ts
  server/src/jobs/importer/formation/builder/organisme.formation.builder.ts
  server/src/jobs/importer/formation/builder/session.formation.builder.test.ts
  server/src/jobs/importer/formation/builder/session.formation.builder.ts
  server/src/jobs/importer/formation/formation.importer.test.ts
  server/src/jobs/importer/formation/formation.importer.ts
  server/src/jobs/importer/organisme/builder/organisme.builder.ts
  server/src/jobs/importer/organisme/organisme.importer.ts
  server/src/jobs/importer/utils/areSourcesUpdated.ts
  server/src/jobs/jobs.ts
  server/src/services/apis/bcn/bcn.test.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/fixtures/index.ts
  shared/src/models/fixtures/organisme.model.fixture.ts
  shared/src/models/fixtures/source.referentiel.model.fixture.ts
  shared/src/models/formation.model.ts
  shared/src/models/import.meta.model.ts
  shared/src/models/models.ts
  shared/src/models/source/referentiel/source.referentiel.model.ts
  yarn.lock
Labels: ignore-for-release

#279 chore: update de la seed
  .infra/files/configs/mongodb/seed.gpg
  .talismanrc
  server/src/migrations/20250102153339-commune.ts
Labels: ignore-for-release

#282 feat: route de recherche de formations
  sdk/src/models/certification/certification.primitives.ts
  sdk/src/routes/common.routes.ts
  sdk/src/routes/formation.routes.ts
  sdk/src/routes/index.ts
  server/src/jobs/importer/certifications/builder/certification.builder.test.ts
  server/src/jobs/importer/certifications/certifications.importer.test.ts
  server/src/jobs/importer/certifications/process/continuite.process.test.ts
  server/src/jobs/importer/certifications/process/coverage.process.test.ts
  server/src/jobs/importer/formation/builder/_.formation.builder.test.ts
  server/src/jobs/importer/formation/builder/certification.formation.builder.test.ts
  server/src/jobs/importer/formation/builder/organisme.formation.builder.test.ts
  server/src/jobs/importer/formation/formation.importer.test.ts
  server/src/server/routes/certification.route.test.ts
  server/src/server/routes/formations/__snapshots__/formations.route.test.ts.snap
  server/src/server/routes/formations/formations.route.test.ts
  server/src/server/routes/formations/formations.routes.ts
  server/src/server/routes/routes.ts
  server/src/services/formation/formation.service.test.ts
  server/src/services/formation/formation.service.ts
  shared/src/models/fixtures/certification.model.fixture.ts
  shared/src/models/fixtures/formation.model.fixture.ts
  shared/src/models/fixtures/index.ts
  shared/src/models/fixtures/organisme.model.fixture.ts
  shared/src/models/formation.model.ts
  shared/src/routes/formation.routes.ts
  shared/src/routes/index.test.ts
  shared/src/routes/index.ts
Labels: enhancement

#284 feat: ajout route prise de rendez-vous
  .talismanrc
  README.md
  docs/developpement/ajouter-route-lba.md
  sdk/src/routes/formation/formation.routes.ts
  server/src/server/routes/formations/formations.route.test.ts
  server/src/server/routes/formations/formations.routes.ts
  shared/src/routes/formation.routes.ts
  shared/src/routes/index.ts
Labels: enhancement

#286 chore: simplification du schema
  sdk/src/routes/certification/certification.routes.openapi.ts
  sdk/src/routes/certification/certification.routes.ts
  sdk/src/routes/common.routes.ts
  sdk/src/routes/formation/formation.routes.ts
  sdk/src/routes/geographie/geographie.routes.openapi.ts
  sdk/src/routes/geographie/geographie.routes.ts
  sdk/src/routes/jobs/job.routes.ts
  sdk/src/routes/organisme/organisme.routes.ts
  sdk/src/utils/zodWithOpenApi.ts
  shared/src/routes/common.routes.ts
  shared/src/routes/experimental/source/acce.routes.ts
  shared/src/routes/healthcheck.routes.ts
Labels: ignore-for-release

#287 chore: refactor route doc definition
  sdk/src/internal.ts
  sdk/src/models/certification/certification.model.openapi.ts
  sdk/src/models/geographie/commune.model.openapi.ts
  sdk/src/models/geographie/departement.model.openapi.ts
  sdk/src/models/geographie/mission-locale.model.openapi.ts
  sdk/src/models/job/job.model.openapi.ts
  sdk/src/openapi/openapiSpec.ts
  sdk/src/openapi/tags.openapi.ts
  sdk/src/openapi/types.ts
  sdk/src/openapi/zodWithOpenApi.ts
  sdk/src/routes/certification/certification.routes.openapi.ts
  sdk/src/routes/certification/certification.routes.ts
  sdk/src/routes/geographie/geographie.routes.openapi.ts
  sdk/src/routes/jobs/job.routes.openapi.ts
  sdk/src/routes/organisme/organisme.routes.openapi.ts
  sdk/src/utils/date.primitives.ts
  sdk/src/utils/index.ts
  server/src/server/server.ts
  server/src/services/documentation/checkDocumentationSync.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/openapi/compareOpenapiStructure.ts
  shared/src/openapi/generateOpenapi.test.ts
  shared/src/openapi/generateOpenapi.ts
  shared/src/routes/healthcheck.routes.ts
Labels: ignore-for-release

#289 chore: add test to openapi spec
  .vscode/launch.json
  sdk/src/models/certification/certification.model.openapi.ts
  sdk/src/models/certification/certification.model.ts
  sdk/src/models/geographie/commune.model.openapi.ts
  sdk/src/models/geographie/commune.model.ts
  sdk/src/models/geographie/departement.model.openapi.ts
  sdk/src/models/geographie/departement.model.ts
  sdk/src/models/geographie/mission-locale.model.openapi.ts
  sdk/src/models/geographie/mission-locale.model.ts
  sdk/src/models/job/job.model.openapi.ts
  sdk/src/openapi/__snapshots__/openapiSpec.test.ts.snap
  sdk/src/openapi/builder/openapi.builder.ts
  sdk/src/openapi/compare/compareOpenapiSchema.ts
  sdk/src/openapi/internal.ts
  sdk/src/openapi/openapiSpec.test.ts
  sdk/src/openapi/types.ts
  sdk/src/openapi/utils/openapi.uils.ts
  sdk/src/openapi/utils/stripDescriptions.openapi.ts
  sdk/src/openapi/utils/zodWithOpenApi.ts
  sdk/src/routes/geographie/geographie.routes.ts
  sdk/src/routes/index.ts
  sdk/src/utils/date.primitives.ts
  sdk/src/utils/index.ts
  server/src/services/documentation/checkDocumentationSync.ts
  server/src/services/documentation/expectedDocumentationDelta.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
  shared/src/openapi/generateOpenapi.test.ts
  shared/src/openapi/generateOpenapi.ts
Labels: ignore-for-release

#290 chore: ajout du guide pour la création d'une route
  .gitignore
  README.md
  docs/developpement/ajouter-route-lba.md
  docs/developpement/creer-route.md
  sdk/src/docs/internal.ts
  sdk/src/docs/metier/recherche-offre/recherche-offre.doc.ts
  sdk/src/docs/models/certification/certification.model.doc.ts
  sdk/src/docs/models/commune/commune.model.doc.ts
  sdk/src/docs/models/departement/departement.model.doc.ts
  sdk/src/docs/models/job/application.model.doc.ts
  sdk/src/docs/models/job/offer_read.model.doc.ts
  sdk/src/docs/models/job/offer_write.model.doc.ts
  sdk/src/docs/models/job/recruiter.model.doc.ts
  sdk/src/docs/models/mission-locale/mission-locale.model.doc.ts
  sdk/src/docs/routes/communeSearch/communeSearch.route.doc.ts
  sdk/src/docs/routes/getCertifications/getCertifications.route.doc.ts
  sdk/src/docs/routes/jobApply/jobApply.route.doc.ts
  sdk/src/docs/routes/jobOfferCreate/jobOfferCreate.route.doc.ts
  sdk/src/docs/routes/jobSearch/jobSearch.route.doc.ts
  sdk/src/docs/routes/listDepartements/listDepartements.route.doc.ts
  sdk/src/docs/routes/listMissionLocales/listMissionLocales.route.doc.ts
  sdk/src/docs/types.ts
  sdk/src/models/formation/formation.model.openapi.ts
  sdk/src/openapi/builder/openapi.builder.ts
  sdk/src/openapi/internal.ts
  sdk/src/openapi/openapiSpec.test.ts
  sdk/src/openapi/tools/initTechnicalDocFromSource.openapi.ts
  sdk/src/openapi/types.ts
  sdk/src/openapi/utils/openapi.uils.ts
  sdk/src/openapi/utils/zodWithOpenApi.ts
  sdk/src/routes/certification/certification.routes.openapi.ts
  sdk/src/types/fastify-swagger.d.ts
  server/src/commands.ts
  ui/app/[lang]/explorer/components/CataloguePage.tsx
Labels: ignore-for-release

#291 chore: simplification model doc metier
  sdk/src/docs/metier/candidature-offre/candidature-offre.doc.ts
  sdk/src/docs/metier/certifications/certifications.doc.ts
  sdk/src/docs/metier/depot-offre/depot-offre.doc.ts
  sdk/src/docs/metier/recherche-commune/recherche-commune.doc.ts
  sdk/src/docs/metier/recherche-offre/recherche-offre.doc.ts
  sdk/src/docs/metier/recuperation-departements/recuperation-departements.doc.ts
  sdk/src/docs/metier/recuperation-mission-locales/recuperation-mission-locales.doc.ts
  sdk/src/docs/types.ts
Labels: ignore-for-release

#293 chore: correction de l'acion de mise a jour de la documentation
  .github/workflows/doc_update.yml
Labels: ignore-for-release

#294 fix: mise à jour de la documentation LBA
  sdk/src/docs/metier/candidature-offre/candidature-offre.doc.ts
  sdk/src/docs/metier/depot-offre/depot-offre.doc.ts
  sdk/src/docs/metier/recherche-offre/en/apply.description.md
  sdk/src/docs/metier/recherche-offre/en/apply.description.md.ts
  sdk/src/docs/metier/recherche-offre/en/description.md
  sdk/src/docs/metier/recherche-offre/en/description.md.ts
  sdk/src/docs/metier/recherche-offre/en/offer.description.md
  sdk/src/docs/metier/recherche-offre/en/offer.description.md.ts
  sdk/src/docs/metier/recherche-offre/en/workplace.description.md
  sdk/src/docs/metier/recherche-offre/en/workplace.description.md.ts
  sdk/src/docs/metier/recherche-offre/fr/apply.description.md
  sdk/src/docs/metier/recherche-offre/fr/apply.description.md.ts
  sdk/src/docs/metier/recherche-offre/fr/description.md
  sdk/src/docs/metier/recherche-offre/fr/description.md.ts
  sdk/src/docs/metier/recherche-offre/fr/offer.description.md
  sdk/src/docs/metier/recherche-offre/fr/offer.description.md.ts
  sdk/src/docs/metier/recherche-offre/fr/workplace.description.md
  sdk/src/docs/metier/recherche-offre/fr/workplace.description.md.ts
  sdk/src/docs/metier/recherche-offre/recherche-offre.doc.ts
  sdk/src/docs/routes/jobApply/docs/en/description.doc.md
  sdk/src/docs/routes/jobApply/docs/en/description.doc.md.ts
  sdk/src/docs/routes/jobApply/docs/fr/description.doc.md
  sdk/src/docs/routes/jobApply/docs/fr/description.doc.md.ts
Labels: documentation

#296 feat: affichage bouton demande habilitations conditionnel et lien vers documentation technique pointe vers la bonne operation
  docs/developpement/creer-route.md
  sdk/src/docs/metier/candidature-offre/candidature-offre.doc.ts
  sdk/src/docs/metier/certifications/certifications.doc.ts
  sdk/src/docs/metier/depot-offre/depot-offre.doc.ts
  sdk/src/docs/metier/recherche-commune/recherche-commune.doc.ts
  sdk/src/docs/metier/recherche-offre/recherche-offre.doc.ts
  sdk/src/docs/metier/recuperation-departements/recuperation-departements.doc.ts
  sdk/src/docs/metier/recuperation-mission-locales/recuperation-mission-locales.doc.ts
  sdk/src/docs/types.ts
  sdk/src/openapi/internal.ts
  sdk/src/openapi/openapiSpec.ts
  sdk/src/openapi/types.ts
  server/src/actions/auth.actions.ts
  server/src/server/routes/_private/auth.route.test.ts
  server/src/server/routes/_private/auth.routes.ts
  shared/src/routes/_private/auth.routes.ts
  ui/app/[lang]/auth/inscription/page.tsx
  ui/app/[lang]/explorer/components/BesoinDesDonnees.tsx
  ui/app/[lang]/explorer/components/CatalogueData.tsx
  ui/app/[lang]/explorer/components/CatalogueHeadline.tsx
  ui/app/[lang]/explorer/components/HabilitationRequise.tsx
  ui/app/[lang]/explorer/components/SwaggerLink.tsx
  ui/app/[lang]/explorer/recherche-commune/page.tsx
  ui/app/[lang]/explorer/recherche-offre/page.tsx
  ui/app/[lang]/explorer/recuperation-departements/page.tsx
  ui/app/[lang]/explorer/recuperation-mission-locales/page.tsx
  ui/app/[lang]/layout.tsx
  ui/app/i18n/locales/en/explorer.json
  ui/app/i18n/locales/fr/explorer.json
  ui/components/header/Header.tsx
  ui/components/header/MonCompteQuickAccess.tsx
  ui/components/link/DsfrLink.tsx
  ui/components/login/withAuth.tsx
  ui/context/AuthContext.tsx
Labels: ignore-for-release

#297 feat: add formation technical documentation
  sdk/src/docs/models/commune/commune.model.doc.ts
  sdk/src/docs/models/formation/formation.model.doc.ts
  sdk/src/docs/models/geoJson/geoJson.model.doc.ts
  sdk/src/docs/models/job/recruiter.model.doc.ts
  sdk/src/docs/models/mission-locale/mission-locale.model.doc.ts
  sdk/src/docs/models/organisme/organisme.model.doc.ts
  sdk/src/docs/routes/searchFormations/searchFormations.route.doc.ts
  sdk/src/models/formation/formation.model.openapi.ts
  sdk/src/models/formation/formation.model.ts
  sdk/src/models/geographie/commune.model.openapi.ts
  sdk/src/models/geographie/geoJson.model.openapi.ts
  sdk/src/models/geographie/geoJson.model.ts
  sdk/src/models/geographie/mission-locale.model.openapi.ts
  sdk/src/models/job/job.model.openapi.ts
  sdk/src/models/organisme/organisme.model.openapi.ts
  sdk/src/models/organisme/organisme.model.ts
  sdk/src/openapi/__snapshots__/openapiSpec.test.ts.snap
  sdk/src/openapi/openapiSpec.ts
  sdk/src/openapi/tags.openapi.ts
  sdk/src/routes/certification/certification.routes.openapi.ts
  sdk/src/routes/formation/formation.routes.openapi.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: documentation

#299 fix: prevent deleting root /tmp directory
  server/src/utils/apiUtils.ts
Labels: bug

#298 chore: upgrade dependencies
  package.json
  sdk/package.json
  server/package.json
  server/src/server/middlewares/apiKeyUsageMiddleware.ts
  server/src/server/middlewares/errorMiddleware.ts
  server/src/server/routes/_private/auth.route.test.ts
  server/src/services/apis/acce/acce.ts
  server/src/services/apis/client.ts
  server/src/services/apis/entreprise/entreprise.ts
  server/src/services/apis/insee/insee.ts
  shared/package.json
  ui/app/[lang]/accessibilite/page.tsx
  ui/app/[lang]/admin/organisations/[id]/page.tsx
  ui/app/[lang]/admin/organisations/page.tsx
  ui/app/[lang]/admin/processeur/cron/[name]/[id]/page.tsx
  ui/app/[lang]/admin/processeur/cron/[name]/page.tsx
  ui/app/[lang]/admin/processeur/job/[name]/[id]/page.tsx
  ui/app/[lang]/admin/processeur/job/[name]/page.tsx
  ui/app/[lang]/admin/processeur/page.tsx
  ui/app/[lang]/admin/utilisateurs/[id]/page.tsx
  ui/app/[lang]/admin/utilisateurs/page.tsx
  ui/app/[lang]/auth/inscription/page.tsx
  ui/app/[lang]/auth/refus-inscription/page.tsx
  ui/app/[lang]/cgu/page.tsx
  ui/app/[lang]/compte/layout.tsx
  ui/app/[lang]/compte/profil/page.tsx
  ui/app/[lang]/documentation-technique/page.tsx
  ui/app/[lang]/documentation-technique/try/page.tsx
  ui/app/[lang]/donnees-personnelles/page.tsx
  ui/app/[lang]/explorer/candidature-offre/page.tsx
  ui/app/[lang]/explorer/certifications/page.tsx
  ui/app/[lang]/explorer/depot-offre/page.tsx
  ui/app/[lang]/explorer/page.tsx
  ui/app/[lang]/explorer/recherche-commune/page.tsx
  ui/app/[lang]/explorer/recherche-offre/page.tsx
  ui/app/[lang]/explorer/recuperation-departements/page.tsx
  ui/app/[lang]/explorer/recuperation-mission-locales/page.tsx
  ui/app/[lang]/explorer/simulateur-npec/page.tsx
  ui/app/[lang]/layout.tsx
  ui/app/[lang]/mentions-legales/page.tsx
  ui/app/[lang]/page.tsx
  ui/app/[lang]/politique-confidentialite/page.tsx
  ui/app/i18n/StartIntl.tsx
  ui/app/i18n/settings.ts
  ui/components/login/withAuth.tsx
  ui/next.config.mjs
  ui/package.json
  ui/robots.ts
  ui/tsconfig.json
  ui/utils/api.utils.ts
  yarn.lock
Labels: dependencies

#301 fix: mise à jour de la doc des routes LBA
  .talismanrc
  sdk/src/docs/metier/candidature-offre/candidature-offre.doc.ts
  sdk/src/docs/metier/depot-offre/depot-offre.doc.ts
  sdk/src/docs/metier/recherche-offre/en/apply.description.md
  sdk/src/docs/metier/recherche-offre/en/apply.description.md.ts
  sdk/src/docs/metier/recherche-offre/fr/apply.description.md
  sdk/src/docs/metier/recherche-offre/fr/apply.description.md.ts
  sdk/src/docs/metier/recherche-offre/fr/offer.description.md
  sdk/src/docs/metier/recherche-offre/fr/offer.description.md.ts
  sdk/src/docs/routes/jobApply/jobApply.route.doc.ts
  sdk/src/docs/routes/jobSearch/jobSearch.route.doc.ts
  ui/app/i18n/locales/en/global.json
  ui/app/i18n/locales/fr/global.json
Labels: documentation

#302 feat: documentation métier de la route de recherche de formations
  sdk/src/docs/metier/candidature-offre/candidature-offre.doc.ts
  sdk/src/docs/metier/certifications/certifications.doc.ts
  sdk/src/docs/metier/depot-offre/depot-offre.doc.ts
  sdk/src/docs/metier/internal.ts
  sdk/src/docs/metier/recherche-commune/recherche-commune.doc.ts
  sdk/src/docs/metier/recherche-formation/recherche-formation.doc.ts
  sdk/src/docs/metier/recherche-offre/recherche-offre.doc.ts
  sdk/src/docs/metier/recuperation-departements/recuperation-departements.doc.ts
  sdk/src/docs/metier/recuperation-mission-locales/recuperation-mission-locales.doc.ts
  sdk/src/docs/routes/communeSearch/communeSearch.route.doc.ts
  sdk/src/docs/routes/getCertifications/getCertifications.route.doc.ts
  sdk/src/docs/routes/jobApply/jobApply.route.doc.ts
  sdk/src/docs/routes/jobOfferCreate/jobOfferCreate.route.doc.ts
  sdk/src/docs/routes/jobSearch/jobSearch.route.doc.ts
  sdk/src/docs/routes/listDepartements/listDepartements.route.doc.ts
  sdk/src/docs/routes/listMissionLocales/listMissionLocales.route.doc.ts
  sdk/src/docs/routes/searchFormations/searchFormations.route.doc.ts
  sdk/src/docs/types.ts
  sdk/src/openapi/openapiSpec.test.ts
  sdk/src/openapi/utils/zodWithOpenApi.ts
  sdk/src/routes/formation/formation.routes.openapi.ts
  server/tests/globalSetup.ts
  ui/app/[lang]/explorer/components/CatalogueData.tsx
  ui/app/[lang]/explorer/components/CataloguePage.tsx
  ui/app/[lang]/explorer/page.tsx
  ui/app/[lang]/explorer/recherche-formation/page.tsx
  ui/app/i18n/locales/en/global.json
  ui/app/i18n/locales/fr/global.json
  ui/next.config.mjs
  ui/utils/routes.utils.ts
Labels: documentation

#303 feat: ajout documentation rdva
  sdk/src/docs/internal.ts
  sdk/src/docs/metier/generation-lien-prise-rdv-formation/generation-lien-prise-rdv-formation.doc.ts
  sdk/src/docs/metier/internal.ts
  sdk/src/docs/routes/generateFormationAppointmentLink/generateFormationAppointmentLink.doc.ts
  sdk/src/routes/formation/formation.routes.openapi.ts
  server/src/services/documentation/checkDocumentationSync.ts
  server/src/services/documentation/expectedDocumentationDelta.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
  ui/app/[lang]/explorer/generation-lien-prise-rdv-formation/page.tsx
  ui/app/[lang]/explorer/page.tsx
  ui/utils/routes.utils.ts
Labels: documentation

#304 fix: build UI edge runtime
  sdk/src/openapi/utils/openapi.uils.ts
  sdk/src/routes/formation/formation.routes.ts
  server/src/commands.ts
  server/src/server/routes/formations/formations.route.test.ts
  server/src/server/routes/job/job.route.test.ts
  server/src/services/documentation/checkDocumentationSync.ts
  server/src/services/documentation/expectedDocumentationDelta.ts
Labels: bug

#305 fix: npec importer tests
  server/src/services/excel/excel.parser.ts
Labels: bug

#308 fix: typo
  sdk/src/docs/metier/depot-offre/depot-offre.doc.ts
Labels: documentation

#309 feat: ajout d'une page admin importers
  server/package.json
  server/src/jobs/importer/acce/acce.ts
  server/src/jobs/importer/bcn/bcn.importer.ts
  server/src/jobs/importer/catalogue/catalogue.importer.ts
  server/src/jobs/importer/certifications/certifications.importer.ts
  server/src/jobs/importer/commune/commune.importer.ts
  server/src/jobs/importer/dares/ape_idcc/dares.ape_idcc.importer.ts
  server/src/jobs/importer/dares/ccn/dares.ccn.importer.ts
  server/src/jobs/importer/formation/formation.importer.ts
  server/src/jobs/importer/france_competence/france_competence.importer.ts
  server/src/jobs/importer/importers.ts
  server/src/jobs/importer/kali/kali.ccn.importer.ts
  server/src/jobs/importer/kit/kitApprentissage.importer.ts
  server/src/jobs/importer/npec/npec.importer.ts
  server/src/jobs/importer/organisme/organisme.importer.ts
  server/src/jobs/importer/referentiel/referentiel.ts
  server/src/jobs/importer/types.ts
  server/src/jobs/jobs.ts
  server/src/server/routes/_private/admin/importer.routes.ts
  server/src/server/routes/routes.ts
  shared/package.json
  shared/src/routes/_private/admin/importers.admin.routes.ts
  shared/src/routes/index.ts
  ui/app/[lang]/admin/hooks/useImporterStatus.ts
  ui/app/[lang]/admin/importers/[name]/page.tsx
  ui/app/[lang]/admin/importers/page.tsx
  ui/app/[lang]/admin/utilisateurs/components/UserList.tsx
  ui/app/i18n/locales/en/global.json
  ui/app/i18n/locales/fr/global.json
  ui/components/header/header.utils.ts
  ui/components/table/Table.tsx
  ui/package.json
  ui/utils/routes.utils.ts
  yarn.lock
Labels: enhancement

#310 fix: importer status with resources
  server/src/jobs/importer/france_competence/france_competence.importer.ts
  server/src/jobs/importer/npec/npec.importer.ts
Labels: bug

#311 fix: wrap buildCertificationContinuity error
  server/src/jobs/importer/certifications/process/coverage.process.ts
Labels: bug

#312 fix: npec importer
  server/src/jobs/importer/npec/npec.importer.ts
  server/src/services/excel/excel.parser.ts
Labels: bug

#313 fix: certification importer
  server/src/jobs/importer/certifications/certifications.importer.ts
  server/src/services/excel/excel.parser.ts
Labels: bug

#314 feat: ajout lieu formation uai
  sdk/src/docs/metier/recherche-formation/recherche-formation.doc.ts
  sdk/src/docs/models/formation/formation.model.doc.ts
  sdk/src/models/formation/formation.model.openapi.ts
  sdk/src/models/formation/formation.model.ts
  server/src/jobs/importer/catalogue/fixtures/sample.ts
  server/src/jobs/importer/formation/builder/_.formation.builder.test.ts
  server/src/jobs/importer/formation/builder/lieu.formation.builder.test.ts
  server/src/jobs/importer/formation/builder/lieu.formation.builder.ts
  server/src/jobs/importer/formation/formation.importer.test.ts
  server/src/migrations/20250121143330-lieu-formation-uai.ts
  server/src/server/routes/formations/__snapshots__/formations.route.test.ts.snap
  server/src/services/apis/catalogue/__snapshots__/catalogue.test.ts.snap
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/fixtures/formation.model.fixture.ts
  shared/src/models/source/catalogue/source.catalogue.model.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: enhancement

#315 feat: ajout route d'export des organismes
  sdk/src/client/internal/organisme/organisme.module.ts
  sdk/src/docs/metier/internal.ts
  sdk/src/docs/metier/recherche-formation/recherche-formation.doc.ts
  sdk/src/docs/metier/recuperation-organismes/recuperation-organismes.doc.ts
  sdk/src/docs/routes/exportOrganismes/exportOrganismes.route.doc.ts
  sdk/src/routes/organisme/organisme.routes.openapi.ts
  sdk/src/routes/organisme/organisme.routes.ts
  server/src/server/routes/organisme.routes.ts
  server/src/server/routes/organismes.routes.test.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
  ui/app/[lang]/explorer/page.tsx
  ui/app/[lang]/explorer/recuperation-organismes/page.tsx
  ui/utils/routes.utils.ts
Labels: enhancement

#317 feat: route d'export des formations
  Dockerfile
  sdk/src/client/client.ts
  sdk/src/client/internal/formation/formation.module.ts
  sdk/src/docs/routes/exportFormations/exportFormations.route.doc.ts
  sdk/src/routes/formation/formation.routes.openapi.ts
  sdk/src/routes/formation/formation.routes.ts
  server/src/server/routes/formations/formations.route.test.ts
  server/src/server/routes/formations/formations.routes.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: enhancement

#318 feat: param to include archived formations in search result
  sdk/src/client/internal/formation/formation.module.ts
  sdk/src/docs/routes/exportFormations/exportFormations.route.doc.ts
  sdk/src/docs/routes/searchFormations/searchFormations.route.doc.ts
  sdk/src/routes/formation/formation.routes.openapi.ts
  sdk/src/routes/formation/formation.routes.ts
  server/src/server/routes/formations/formations.route.test.ts
  server/src/server/routes/formations/formations.routes.ts
  server/src/services/formation/formation.service.test.ts
  server/src/services/formation/formation.service.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: enhancement

#319 feat: pagination de la route d'export organismes
  .vscode/settings.json
  sdk/src/client/internal/organisme/organisme.module.ts
  sdk/src/docs/models/pagination/pagination.model.doc.ts
  sdk/src/docs/routes/exportOrganismes/exportOrganismes.route.doc.ts
  sdk/src/docs/routes/searchFormations/searchFormations.route.doc.ts
  sdk/src/models/certification/certification.model.openapi.ts
  sdk/src/models/errors/errors.model.openapi.ts
  sdk/src/models/formation/formation.model.openapi.ts
  sdk/src/models/geographie/commune.model.openapi.ts
  sdk/src/models/geographie/departement.model.openapi.ts
  sdk/src/models/geographie/geoJson.model.openapi.ts
  sdk/src/models/geographie/mission-locale.model.openapi.ts
  sdk/src/models/index.ts
  sdk/src/models/job/job.model.openapi.ts
  sdk/src/models/organisme/organisme.model.openapi.ts
  sdk/src/models/pagination/pagination.model.openapi.ts
  sdk/src/models/pagination/pagination.model.ts
  sdk/src/openapi/openapiSpec.ts
  sdk/src/openapi/types.ts
  sdk/src/routes/certification/certification.routes.openapi.ts
  sdk/src/routes/formation/formation.routes.openapi.ts
  sdk/src/routes/formation/formation.routes.ts
  sdk/src/routes/geographie/geographie.routes.openapi.ts
  sdk/src/routes/jobs/job.routes.openapi.ts
  sdk/src/routes/organisme/organisme.routes.openapi.ts
  sdk/src/routes/organisme/organisme.routes.ts
  server/src/server/routes/organisme.routes.ts
  server/src/server/routes/organismes.routes.test.ts
  server/src/services/formation/formation.service.ts
  server/src/services/pagination/pagination.service.ts
  shared/src/constants/index.ts
  shared/src/constants/pays.ts
  shared/src/constants/territoires.ts
  shared/src/index.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: enhancement

#320 fix: sdk organisme export function type definition
  sdk/src/client/internal/organisme/organisme.module.ts
Labels: bug

#321 feat: formation module search as async generator
  sdk/src/client/internal/formation/formation.module.ts
Labels: enhancement

#323 feat: ajout des contacts organismes
  .vscode/settings.json
  sdk/src/docs/metier/recuperation-organismes/recuperation-organismes.doc.ts
  sdk/src/docs/models/organisme/organisme.model.doc.ts
  sdk/src/models/organisme/organisme.model.openapi.ts
  sdk/src/models/organisme/organisme.model.ts
  sdk/src/openapi/__snapshots__/openapiSpec.test.ts.snap
  server/src/jobs/importer/formation/builder/organisme.formation.builder.test.ts
  server/src/jobs/importer/formation/builder/organisme.formation.builder.ts
  server/src/jobs/importer/organisme/builder/organisme.builder.ts
  server/src/jobs/importer/organisme/organisme.importer.fixtures.ts
  server/src/jobs/importer/organisme/organisme.importer.test.ts
  server/src/server/routes/formations/__snapshots__/formations.route.test.ts.snap
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/fixtures/organisme.model.fixture.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: enhancement

#324 fix: build
  Dockerfile
Labels: ignore-for-release

#325 fix: ajout de la migration contacts
  server/src/migrations/20250129090921-contact-migration.ts
Labels: bug

#326 fix: pagination query param coerce string to number
  sdk/src/models/pagination/pagination.model.ts
  sdk/src/openapi/__snapshots__/openapiSpec.test.ts.snap
Labels: bug

#328 fix: organismes export with query params
  sdk/src/models/pagination/pagination.model.ts
  sdk/src/openapi/__snapshots__/openapiSpec.test.ts.snap
Labels: bug

#329 feat: correction des labels / orthographe
  sdk/src/docs/metier/recherche-formation/recherche-formation.doc.ts
  sdk/src/docs/routes/jobSearch/jobSearch.route.doc.ts
  server/src/services/documentation/expectedDocumentationDelta.ts
  server/src/services/security/authenticationService.test.ts
Labels: ignore-for-release
