Repository mission-apprentissage/api-apprentissage, pull requests merged in 2025-02, with the labels that each got.

#331 feat: add Kit_apprentissage_20250131
  server/static/kit_apprentissage/Kit_apprentissage_20250131.xlsx
Labels: enhancement

#332 feat: correction documentation target_diploma_level
  sdk/src/docs/routes/jobSearch/parameters/target_diploma_level.md
  sdk/src/docs/routes/jobSearch/parameters/target_diploma_level.md.ts
Labels: documentation

#330 feat: ajout de mécanisme de suppression d'organisation
  server/src/actions/organisations.actions.ts
  server/src/server/routes/_private/admin/organisations.routes.ts
  shared/src/routes/_private/admin/organisation.admin.routes.ts
  shared/src/routes/index.ts
  ui/app/[lang]/admin/hooks/useDeleteOrganisation.ts
  ui/app/[lang]/admin/organisations/components/OrganisationList.tsx
Labels: ignore-for-release

#333 feat: update tech doc for post/apply route
  sdk/src/docs/routes/generateFormationAppointmentLink/generateFormationAppointmentLink.doc.ts
Labels: documentation

#334 feat: force refresh post delete organisation
  ui/app/[lang]/admin/hooks/useDeleteOrganisation.ts
Labels: enhancement

#335 feat: import kit apprentissage via API
  .infra/.env_server
  .infra/files/configs/mongodb/seed.gpg
  .infra/vault/vault.yml
  .talismanrc
  server/.env.test
  server/src/config.ts
  server/src/jobs/importer/certifications/builder/certification.builder.test.ts
  server/src/jobs/importer/certifications/certifications.importer.test.ts
  server/src/jobs/importer/certifications/certifications.importer.ts
  server/src/jobs/importer/france_competence/france_competence.importer.ts
  server/src/jobs/importer/kit/__snapshots__/kitApprentissage.importer.test.ts.snap
  server/src/jobs/importer/kit/builder/kit_apprentissage.builder.test.ts
  server/src/jobs/importer/kit/builder/kit_apprentissage.builder.ts
  server/src/jobs/importer/kit/fixtures/empty/kit_apprentissage/.gitkeep
  server/src/jobs/importer/kit/kitApprentissage.importer.test.ts
  server/src/jobs/importer/kit/kitApprentissage.importer.ts
  server/src/jobs/indicateurs/source/kitApprentissage.source.indicateur.test.ts
  server/src/jobs/indicateurs/source/kitApprentissage.source.indicateur.ts
  server/src/migrations/20250205153716-kit-apprentissage.ts
  server/src/services/apis/kit_apprentissage/kit_apprentissage.api.test.ts
  server/src/services/apis/kit_apprentissage/kit_apprentissage.api.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/fixtures/source.kit_apprentissage.model.fixture.ts
  shared/src/models/indicateurs/source_kit_apprentissage.model.ts
  shared/src/models/source/kitApprentissage/source.kit_apprentissage.model.ts
Labels: ignore-for-release

#337 feat: recherche de mission locale par geolocalisation
  sdk/src/client/internal/geographie/geographie.module.ts
  sdk/src/docs/routes/listMissionLocales/listMissionLocales.route.doc.ts
  sdk/src/openapi/__snapshots__/openapiSpec.test.ts.snap
  sdk/src/routes/geographie/geographie.routes.openapi.ts
  sdk/src/routes/geographie/geographie.routes.ts
  server/src/server/routes/geographie.route.ts
  server/src/services/geographie/geographie.service.test.ts
  server/src/services/geographie/geographie.service.ts
  shared/src/models/commune.model.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: enhancement

#338 feat: ajout du geopoint de l'etablissement d'un organisme
  sdk/src/docs/metier/recuperation-organismes/recuperation-organismes.doc.ts
  sdk/src/docs/models/organisme/organisme.model.doc.ts
  sdk/src/models/organisme/organisme.model.openapi.ts
  sdk/src/models/organisme/organisme.model.ts
  sdk/src/openapi/__snapshots__/openapiSpec.test.ts.snap
  server/src/config.ts
  server/src/jobs/importer/organisme/builder/organisme.builder.ts
  server/src/jobs/importer/organisme/organisme.importer.fixtures.ts
  server/src/jobs/importer/organisme/organisme.importer.test.ts
  server/src/migrations/20250212130220-organisme-location.ts
  server/src/server/routes/formations/__snapshots__/formations.route.test.ts.snap
  server/src/services/apis/adresse/adresse.test.ts
  server/src/services/apis/adresse/adresse.ts
  shared/src/apis/adresse_gouv.ts
  shared/src/apis/index.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/fixtures/organisme.model.fixture.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: enhancement

#340 fix: cron monitor check-in
  .infra/docker-compose.production.yml
  server/package.json
  server/src/jobs/importer/importers.ts
  shared/package.json
  ui/package.json
  yarn.lock
Labels: ignore-for-release

#341 feat: correction de l'orthographe
  sdk/src/docs/metier/candidature-offre/candidature-offre.doc.ts
  sdk/src/docs/metier/certifications/certifications.doc.ts
  sdk/src/docs/metier/certifications/fr/continuite.description.md
  sdk/src/docs/metier/certifications/fr/continuite.description.md.ts
  sdk/src/docs/metier/certifications/fr/domaines.description.md
  sdk/src/docs/metier/certifications/fr/domaines.description.md.ts
  sdk/src/docs/metier/certifications/fr/identifiant.information.md
  sdk/src/docs/metier/certifications/fr/identifiant.information.md.ts
  sdk/src/docs/metier/certifications/fr/identifiant.tip.md
  sdk/src/docs/metier/certifications/fr/identifiant.tip.md.ts
  sdk/src/docs/metier/certifications/fr/intitule.description.md
  sdk/src/docs/metier/certifications/fr/intitule.description.md.ts
  sdk/src/docs/metier/certifications/fr/intitule.niveau.tip.md
  sdk/src/docs/metier/certifications/fr/intitule.niveau.tip.md.ts
  sdk/src/docs/metier/certifications/fr/periode_validite.cfd.description.md
  sdk/src/docs/metier/certifications/fr/periode_validite.cfd.description.md.ts
  sdk/src/docs/metier/certifications/fr/periode_validite.rncp.description.md
  sdk/src/docs/metier/certifications/fr/periode_validite.rncp.description.md.ts
  sdk/src/docs/metier/certifications/fr/type.description.md
  sdk/src/docs/metier/certifications/fr/type.description.md.ts
  sdk/src/docs/metier/depot-offre/depot-offre.doc.ts
  sdk/src/docs/metier/generation-lien-prise-rdv-formation/generation-lien-prise-rdv-formation.doc.ts
  sdk/src/docs/metier/recherche-formation/recherche-formation.doc.ts
  sdk/src/docs/metier/recuperation-organismes/recuperation-organismes.doc.ts
  sdk/src/docs/models/certification/certification.model.doc.ts
  sdk/src/docs/models/formation/formation.model.doc.ts
  ui/app/[lang]/accessibilite/components/Accessibilite.tsx
  ui/app/[lang]/donnees-personnelles/components/DonneesPersonnelles.tsx
  ui/app/[lang]/explorer/page.tsx
  ui/app/[lang]/mentions-legales/components/MentionLegales.tsx
  ui/app/[lang]/politique-confidentialite/components/PolitiqueConfidentialite.tsx
Labels: documentation

#343 feat: update wording impératif
  sdk/src/docs/metier/recherche-formation/recherche-formation.doc.ts
  sdk/src/docs/metier/recuperation-organismes/recuperation-organismes.doc.ts
  sdk/src/docs/routes/jobSearch/jobSearch.route.doc.ts
Labels: documentation

#344 fix: correction migration organismes
  server/src/jobs/importer/importers.ts
  server/src/jobs/importer/organisme/builder/organisme.builder.ts
  server/src/jobs/importer/organisme/organisme.importer.ts
  server/src/jobs/jobs.ts
  server/src/migrations/20250212130220-organisme-location.ts
  server/src/migrations/20250212160910-organisme-geopoint.ts
  server/src/services/apis/adresse/adresse.api.test.ts
  server/src/services/apis/adresse/adresse.api.ts
  server/src/services/apis/adresse/adresse.ts
  server/src/services/apis/entreprise/entreprise.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/cache/cache.adresse.model.ts
  shared/src/models/cache/cache.entreprise.model.ts
  shared/src/models/models.ts
Labels: ignore-for-release

#345 feat: update wording email
  ui/app/i18n/locales/en/inscription-connexion.json
  ui/app/i18n/locales/fr/inscription-connexion.json
Labels: enhancement

#346 chore: mise à jour du model indicateur.usage_api
  server/src/migrations/20250218100831-indicateur_usage.ts
  server/src/server/middlewares/apiKeyUsageMiddleware.test.ts
  server/src/server/middlewares/apiKeyUsageMiddleware.ts
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/indicateurs/usage_api.model.ts
Labels: ignore-for-release

#347 fix: exemple post job valeur target_diploma.european
  sdk/src/docs/models/job/offer_read.model.doc.ts
Labels: documentation

#348 fix: empty string enseigne
  sdk/src/models/organisme/organisme.model.ts
  server/src/migrations/20250218152657-organisme-enseigne.ts
Labels: ignore-for-release

#349 fix: organisme personne_physique
  server/package.json
  server/src/jobs/importer/organisme/builder/organisme.builder.ts
  server/src/jobs/importer/organisme/organisme.importer.fixtures.ts
  server/src/migrations/20250219094006-personne_physique.ts
  server/src/services/apis/entreprise/entreprise.test.ts
  server/src/services/apis/entreprise/entreprise.ts
  shared/package.json
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/cache/cache.entreprise.model.ts
  ui/package.json
  yarn.lock
Labels: ignore-for-release

#350 fix: cache_entreprise migration model
  server/src/migrations/20250219120014-cache_entreprise_validation.ts
Labels: ignore-for-release

#352 feat: expose api-alternance-sdk fixtures
  sdk/package.json
  sdk/src/fixtures.ts
  sdk/src/fixtures/certification.model.fixture.ts
  sdk/src/fixtures/formation.model.fixture.ts
  sdk/src/fixtures/organisme.model.fixture.ts
  server/src/jobs/importer/certifications/certifications.importer.test.ts
  server/src/server/routes/formations/formations.route.test.ts
  server/src/services/formation/formation.service.test.ts
  shared/src/models/fixtures/certification.model.fixture.ts
  shared/src/models/fixtures/formation.model.fixture.ts
  shared/src/models/fixtures/organisme.model.fixture.ts
Labels: enhancement

#354 feat: ajout de fixtures
  sdk/src/fixtures.ts
  sdk/src/fixtures/cfd.fixture.ts
  sdk/src/fixtures/rncp.fixture.ts
  sdk/src/fixtures/siret.fixture.ts
  sdk/src/fixtures/uai.fixture.ts
Labels: enhancement

#355 fix: commune importer
  shared/src/apis/unml.ts
Labels: ignore-for-release

#356 fix: add querystring to listMissionLocales
  sdk/src/client/internal/geographie/geographie.module.test.ts
  sdk/src/client/internal/geographie/geographie.module.ts
Labels: bug

#357 fix: recherche formation include_archived query param
  sdk/src/client/internal/formation/__snapshots__/formation.module.test.ts.snap
  sdk/src/client/internal/formation/formation.module.test.ts
  sdk/src/routes/formation/formation.routes.openapi.ts
  sdk/src/routes/formation/formation.routes.ts
  server/src/server/routes/formations/formations.route.test.ts
  shared/src/openapi/__snapshots__/generateOpenapi.test.ts.snap
Labels: bug

#360 fix: skip import when source import failed
  server/src/jobs/importer/certifications/certifications.importer.ts
  server/src/jobs/importer/formation/formation.importer.ts
  server/src/jobs/importer/organisme/organisme.importer.ts
  server/src/jobs/importer/utils/areSourcesUpdated.ts
Labels: ignore-for-release
