Repository mission-apprentissage/api-apprentissage, pull requests merged in 2025-05, with the labels that each got.

#388 fix: smtp
  .infra/vault/vault.yml
Labels: ignore-for-release

#389 feat: update CORS policy for data.gouv.fr
  server/src/server/server.ts
Labels: enhancement

#391 fix: data gouv CORS issue
  server/src/server/server.ts
Labels: bug

#385 feat: ajout d'un job de notification des clés API
  server/src/actions/users.actions.ts
  server/src/jobs/apiKey/apiKeyExpiration.notifier.test.ts
  server/src/jobs/apiKey/apiKeyExpiration.notifier.ts
  server/src/jobs/jobs.ts
  server/src/migrations/20250523140713-key-notif-expire.ts
  server/src/server/routes/_private/user.route.test.ts
  server/src/services/mailer/mailer.ts
  server/src/services/security/authenticationService.test.ts
  server/static/emails/api-key-will-expire.mjml.ejs
  shared/src/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap
  shared/src/models/email_event/email_templates.ts
  shared/src/models/user.model.ts
Labels: enhancement
